### ISSUE TITLE
/proc/0/fd/0?

### ISSUE THREAD

**Issue by jiangxuelei** [opencontainers/runc#2707] opened 2020-12-10 17:19 UTC
Got an error while i exec "runc create test":

WARN[0000] exit status 1
ERRO[0000] container_linux.go:370: starting container process caused: process_linux.go:346: getting pipe fds for pid 0 caused: readlink /proc/0/fd/0: no such file or directory

what's the problem?   why pid is 0?

**Comment by kolyshkin** [comment] 2020-12-18 21:53
It looks like some code in libcontainer/process_linux.go failed to properly receive child pid (or error), thus we have this.

@jiangxuelei alas, it is impossible to investigate unless you provide us with some more info (like, which runc version) and a complete reproducer -- what to run to get the same result as you did. Please consider providing this.

**Comment by kolyshkin** [comment] 2021-01-04 18:54
Not much info to investigate further, closing for now unless @jiangxuelei will give more details.

**Closed by kolyshkin** 2021-01-04 18:54 UTC
Labels: question
