### ISSUE TITLE
`integration_systemd_rootless` on Fedora began to fail

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#3266] opened 2021-11-08 08:43 UTC
`integration_systemd_rootless` on Fedora began to fail after commit https://github.com/opencontainers/runc/commit/86829836480f36429403ff4c0d52414fb7493d23 (`Merge pull request #3264 from thaJeztah/cirrus_go_version`, Nov 8, 2021).

https://github.com/opencontainers/runc/runs/4135786850

```
# runc spec --rootless (status=0):
# 
# runc run -d --console-socket /tmp/bats-run-ReiKHb/runc.4aWdGN/tty/sock test_update (status=1):
# time="2021-11-08T07:22:53Z" level=error msg="runc run failed: unable to start container process: unable to apply cgroup configuration: unable to start unit \"runc-cgroups-integration-test-28687.scope\" (properties [{Name:Description Value:\"libcontainer container integration-test-28687\"} {Name:Slice Value:\"machine.slice\"} {Name:Delegate Value:true} {Name:PIDs Value:@au [77707]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): error creating systemd unit `runc-cgroups-integration-test-28687.scope`: got `failed`"
not ok 148 update cpuset parameters via resources.CPU
# (in test file /vagrant/tests/integration/update.bats, line 476)
#   `[ "$status" -eq 0 ]' failed
# runc spec --rootless (status=0):
# 
# runc run -d --console-socket /tmp/bats-run-ReiKHb/runc.tIcuDO/tty/sock test_update (status=1):
# time="2021-11-08T07:22:53Z" level=error msg="runc run failed: unable to start container process: unable to apply cgroup configuration: unable to start unit \"runc-cgroups-integration-test-11196.scope\" (properties [{Name:Description Value:\"libcontainer container integration-test-11196\"} {Name:Slice Value:\"machine.slice\"} {Name:Delegate Value:true} {Name:PIDs Value:@au [77798]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): error creating systemd unit `runc-cgroups-integration-test-11196.scope`: got `failed`"
not ok 149 update cpuset parameters via v2 unified map
# (in test file /vagrant/tests/integration/update.bats, line 524)
#   `[ "$status" -eq 0 ]' failed
# runc spec --rootless (status=0):
# 
# runc run -d --console-socket /tmp/bats-run-ReiKHb/runc.FIy8Sf/tty/sock test_update (status=1):
# time="2021-11-08T07:22:54Z" level=error msg="runc run failed: unable to start container process: unable to apply cgroup configuration: unable to start unit \"runc-cgroups-integration-test-31857.scope\" (properties [{Name:Description Value:\"libcontainer container integration-test-31857\"} {Name:Slice Value:\"machine.slice\"} {Name:Delegate Value:true} {Name:PIDs Value:@au [77890]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): error creating systemd unit `runc-cgroups-integration-test-31857.scope`: got `failed`"
ok 150 update rt period and runtime # skip test requires cgroups_v1
ok 151 update devices [minimal transition rules] # skip test requires root
not ok 152 update paused container
# (in test file /vagrant/tests/integration/update.bats, line 690)
#   `[ "$status" -eq 0 ]' failed
# runc spec --rootless (status=0):
# 
# runc run -d --console-socket /tmp/bats-run-ReiKHb/runc.jPHqie/tty/sock test_update (status=1):
# time="2021-11-08T07:22:54Z" level=error msg="runc run failed: unable to start container process: unable to apply cgroup configuration: unable to start unit \"runc-cgroups-integration-test-11181.scope\" (properties [{Name:Description Value:\"libcontainer container integration-test-11181\"} {Name:Slice Value:\"machine.slice\"} {Name:Delegate Value:true} {Name:PIDs Value:@au [78130]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): error creating systemd unit `runc-cgroups-integration-test-11181.scope`: got `failed`"
not ok 153 userns with simple mount
# (in test file /vagrant/tests/integration/userns.bats, line 34)
#   `[ "$status" -eq 0 ]' failed
# runc spec --rootless (status=0):
# 
# runc run test_busybox (status=1):
# time="2021-11-08T07:22:55Z" level=error msg="runc run failed: unable to start container process: unable to apply cgroup configuration: unable to start unit \"runc-test_busybox.scope\" (properties [{Name:Description Value:\"libcontainer container test_busybox\"} {Name:Slice Value:\"user.slice\"} {Name:Delegate Value:true} {Name:PIDs Value:@au [78235]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): error creating systemd unit `runc-test_busybox.scope`: got `failed`"
not ok 154 userns with 2 inaccessible mounts
# (in test file /vagrant/tests/integration/userns.bats, line 52)
#   `[ "$status" -eq 0 ]' failed
# runc spec --rootless (status=0):
# 
# runc run test_busybox (status=1):
# time="2021-11-08T07:22:55Z" level=error msg="runc run failed: unable to start container process: unable to apply cgroup configuration: unable to start unit \"runc-test_busybox.scope\" (properties [{Name:Description Value:\"libcontainer container test_busybox\"} {Name:Slice Value:\"user.slice\"} {Name:Delegate Value:true} {Name:PIDs Value:@au [78309]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): error creating systemd unit `runc-test_busybox.scope`: got `failed`"
not ok 155 userns with inaccessible mount + exec
# (in test file /vagrant/tests/integration/userns.bats, line 62)
#   `[ "$status" -eq 0 ]' failed
# runc spec --rootless (status=0):
# 
# runc run -d --console-socket /tmp/bats-run-ReiKHb/runc.1ui9dS/tty/sock test_busybox (status=1):
# time="2021-11-08T07:22:55Z" level=error msg="runc run failed: unable to start container process: unable to apply cgroup configuration: unable to start unit \"runc-test_busybox.scope\" (properties [{Name:Description Value:\"libcontainer container test_busybox\"} {Name:Slice Value:\"user.slice\"} {Name:Delegate Value:true} {Name:PIDs Value:@au [78383]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): error creating systemd unit `runc-test_busybox.scope`: got `failed`"
ok 156 runc version
Connection to localhost closed.

make: *** [Makefile:100: localrootlessintegration] Error 1
make: Leaving directory '/vagrant'
Connection to 192.168.121.253 closed.

Exit status: 2
```

The previous merge commit https://github.com/opencontainers/runc/commit/ecdc9664718c935376f95846b9627a5bec684d52 (`Merge pull request #3262 from opencontainers/dependabot/go_modules/gi…`) was passing CI.

https://github.com/opencontainers/runc/commits/master

**Comment by AkihiroSuda** [comment] 2021-11-08 08:47
(But I don't think the commit https://github.com/opencontainers/runc/commit/86829836480f36429403ff4c0d52414fb7493d23 is causing any regression. Maybe just some `dnf` dependency got broken.)

**Comment by AkihiroSuda** [comment] 2021-11-08 09:18
journalctl has suspicious logs

```
Nov 08 09:17:31 fedora systemd[41044]: runc-test_cgroups_permissions.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 08 09:17:31 fedora systemd[41044]: runc-test_cgroups_permissions.scope: Failed with result 'resources'.
Nov 08 09:17:31 fedora systemd[41044]: Failed to start libcontainer container test_cgroups_permissions.
Nov 08 09:17:33 fedora systemd[41044]: runc-cgroups-integration-test-19235.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 08 09:17:33 fedora systemd[41044]: runc-cgroups-integration-test-19235.scope: Failed with result 'resources'.
Nov 08 09:17:33 fedora systemd[41044]: Failed to start libcontainer container integration-test-19235.
Nov 08 09:17:34 fedora systemd[41044]: runc-cgroups-integration-test-24935.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 08 09:17:34 fedora systemd[41044]: runc-cgroups-integration-test-24935.scope: Failed with result 'resources'.
Nov 08 09:17:34 fedora systemd[41044]: Failed to start libcontainer container integration-test-24935.
Nov 08 09:17:36 fedora systemd[41044]: runc-cgroups-integration-test-23924.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 08 09:17:36 fedora systemd[41044]: runc-cgroups-integration-test-23924.scope: Failed with result 'resources'.
Nov 08 09:17:36 fedora systemd[41044]: Failed to start libcontainer container integration-test-23924.
Nov 08 09:17:37 fedora systemd[41044]: runc-cgroups-integration-test-14071.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 08 09:17:37 fedora systemd[41044]: runc-cgroups-integration-test-14071.scope: Failed with result 'resources'.
Nov 08 09:17:37 fedora systemd[41044]: Failed to start libcontainer container integration-test-14071.
Nov 08 09:17:39 fedora systemd[41044]: runc-cgroups-integration-test-5339.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 08 09:17:39 fedora systemd[41044]: runc-cgroups-integration-test-5339.scope: Failed with result 'resources'.
Nov 08 09:17:39 fedora systemd[41044]: Failed to start libcontainer container integration-test-5339.
Nov 08 09:17:39 fedora systemd[41044]: runc-cgroups-integration-test-21745.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 08 09:17:39 fedora systemd[41044]: runc-cgroups-integration-test-21745.scope: Failed with result 'resources'.
Nov 08 09:17:39 fedora systemd[41044]: Failed to start libcontainer container integration-test-21745.
Nov 08 09:17:40 fedora systemd[41044]: runc-cgroups-integration-test-2014.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 08 09:17:40 fedora systemd[41044]: runc-cgroups-integration-test-2014.scope: Failed with result 'resources'.
Nov 08 09:17:40 fedora systemd[41044]: Failed to start libcontainer container integration-test-2014.
```

**Comment by kolyshkin** [comment] 2021-11-10 23:58
Apparently this is caused by a recent systemd update.

Good run:
```
Nov 10 13:36:38 kir-rhat systemd[1]: Started User Manager for UID 2000.
Nov 10 13:36:38 kir-rhat audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=user@2000 comm="systemd" exe="/usr/lib/systemd/systemd" hos>
Nov 10 13:36:38 kir-rhat systemd[1]: Started Session 17 of User rootless.
Nov 10 13:36:38 kir-rhat sshd[1947601]: pam_unix(sshd:session): session opened for user rootless(uid=2000) by (uid=0)
Nov 10 13:36:38 kir-rhat audit[1947601]: USER_START pid=1947601 uid=0 auid=2000 ses=17 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_selinux,pam_loginuid,pam>
Nov 10 13:36:38 kir-rhat audit[1947641]: CRYPTO_KEY_USER pid=1947641 uid=0 auid=2000 ses=17 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:d2:07:c0:de:64:bc:1>
Nov 10 13:36:38 kir-rhat audit[1947641]: CRED_ACQ pid=1947641 uid=0 auid=2000 ses=17 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_env,pam_localuser,pam_unix acct>
Nov 10 13:36:38 kir-rhat audit[1947601]: USER_LOGIN pid=1947601 uid=0 auid=2000 ses=17 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login id=2000 exe="/usr/sbin/sshd" hostname=? addr=::1>
Nov 10 13:36:38 kir-rhat audit[1947601]: USER_START pid=1947601 uid=0 auid=2000 ses=17 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login id=2000 exe="/usr/sbin/sshd" hostname=? addr=::1>
Nov 10 13:36:38 kir-rhat audit[1947601]: CRYPTO_KEY_USER pid=1947601 uid=0 auid=2000 ses=17 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:d2:07:c0:de:64:bc:1>
Nov 10 13:36:39 kir-rhat systemd[1947609]: Created slice User Core Session Slice.
Nov 10 13:36:39 kir-rhat systemd[1947609]: Starting D-Bus User Message Bus...
Nov 10 13:36:39 kir-rhat dbus-broker-launch[1948065]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored
Nov 10 13:36:39 kir-rhat dbus-broker-launch[1948065]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated and ignored
Nov 10 13:36:39 kir-rhat systemd[1947609]: Started D-Bus User Message Bus.
Nov 10 13:36:39 kir-rhat dbus-broker-lau[1948065]: Ready
Nov 10 13:36:39 kir-rhat systemd[1947609]: Created slice Slice /user.
Nov 10 13:36:39 kir-rhat systemd[1947609]: runc-test_cgroups_permissions.scope: unit configures an IP firewall, but not running as root.
Nov 10 13:36:39 kir-rhat systemd[1947609]: (This warning is only shown for the first unit using IP firewalling.)
Nov 10 13:36:39 kir-rhat systemd[1947609]: Started libcontainer container test_cgroups_permissions.
Nov 10 13:36:40 kir-rhat systemd[1947609]: Created slice Slice /machine.
Nov 10 13:36:40 kir-rhat systemd[1947609]: Started libcontainer container integration-test-2272.
Nov 10 13:36:40 kir-rhat systemd[1947609]: Started libcontainer container integration-test-14566.
Nov 10 13:36:41 kir-rhat systemd[1947609]: Started libcontainer container integration-test-29225.
Nov 10 13:36:42 kir-rhat systemd[1947609]: Started libcontainer container integration-test-32133.
Nov 10 13:36:43 kir-rhat systemd[1947609]: Started libcontainer container integration-test-23574.
Nov 10 13:36:44 kir-rhat systemd[1947609]: Started libcontainer container integration-test-8202.
```

Bad run:
```
Nov 10 15:40:59 kir-rhat systemd[1]: Started User Manager for UID 2000.
Nov 10 15:40:59 kir-rhat audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=user@2000 comm="systemd" exe="/usr/lib/systemd/systemd" hos>
Nov 10 15:40:59 kir-rhat systemd[1]: Started Session 19 of User rootless.
Nov 10 15:40:59 kir-rhat sshd[2226608]: pam_unix(sshd:session): session opened for user rootless(uid=2000) by (uid=0)
Nov 10 15:40:59 kir-rhat audit[2226608]: USER_START pid=2226608 uid=0 auid=2000 ses=19 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_selinux,pam_loginuid,pam>
Nov 10 15:40:59 kir-rhat audit[2226660]: CRYPTO_KEY_USER pid=2226660 uid=0 auid=2000 ses=19 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:d2:07:c0:de:64:bc:1>
Nov 10 15:40:59 kir-rhat audit[2226660]: CRED_ACQ pid=2226660 uid=0 auid=2000 ses=19 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_env,pam_localuser,pam_unix acct>
Nov 10 15:40:59 kir-rhat audit[2226608]: USER_LOGIN pid=2226608 uid=0 auid=2000 ses=19 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login id=2000 exe="/usr/sbin/sshd" hostname=? addr=::1>
Nov 10 15:40:59 kir-rhat audit[2226608]: USER_START pid=2226608 uid=0 auid=2000 ses=19 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login id=2000 exe="/usr/sbin/sshd" hostname=? addr=::1>
Nov 10 15:40:59 kir-rhat audit[2226608]: CRYPTO_KEY_USER pid=2226608 uid=0 auid=2000 ses=19 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:d2:07:c0:de:64:bc:1>
Nov 10 15:41:00 kir-rhat systemd[2226616]: Created slice User Core Session Slice.
Nov 10 15:41:00 kir-rhat systemd[2226616]: Starting D-Bus User Message Bus...
Nov 10 15:41:00 kir-rhat dbus-broker-launch[2227159]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored
Nov 10 15:41:00 kir-rhat dbus-broker-launch[2227159]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated and ignored
Nov 10 15:41:00 kir-rhat systemd[2226616]: Started D-Bus User Message Bus.
Nov 10 15:41:00 kir-rhat dbus-broker-lau[2227159]: Ready
Nov 10 15:41:00 kir-rhat systemd[2226616]: Created slice Slice /user.
Nov 10 15:41:00 kir-rhat systemd[2226616]: runc-test_cgroups_permissions.scope: unit configures an IP firewall, but not running as root.
Nov 10 15:41:00 kir-rhat systemd[2226616]: (This warning is only shown for the first unit using IP firewalling.)
Nov 10 15:41:00 kir-rhat systemd[2226616]: runc-test_cgroups_permissions.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 10 15:41:00 kir-rhat systemd[2226616]: runc-test_cgroups_permissions.scope: Failed with result 'resources'.
Nov 10 15:41:00 kir-rhat systemd[2226616]: Failed to start libcontainer container test_cgroups_permissions.
Nov 10 15:41:01 kir-rhat systemd[2226616]: Created slice Slice /machine.
Nov 10 15:41:01 kir-rhat systemd[2226616]: runc-cgroups-integration-test-4570.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 10 15:41:01 kir-rhat systemd[2226616]: runc-cgroups-integration-test-4570.scope: Failed with result 'resources'.
Nov 10 15:41:01 kir-rhat systemd[2226616]: Failed to start libcontainer container integration-test-4570.
Nov 10 15:41:02 kir-rhat systemd[2226616]: runc-cgroups-integration-test-29925.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 10 15:41:02 kir-rhat systemd[2226616]: runc-cgroups-integration-test-29925.scope: Failed with result 'resources'.
Nov 10 15:41:02 kir-rhat systemd[2226616]: Failed to start libcontainer container integration-test-29925.
```

The difference is systemd version:
* good: v249.4-2.fc35
* bad: systemd-249.6-2.fc35.x86_64

Looking at the sources, I see too much changes: (top commits from https://src.fedoraproject.org/rpms/systemd/commits/f35)

**Comment by kolyshkin** [comment] 2021-11-11 00:04
Probably caused by https://github.com/systemd/systemd/pull/21163/commits/8d3e4ac7cd37200d1431411a4b98925a24b7d9b3 ... looking

**Comment by kolyshkin** [comment] 2021-11-11 02:55
I think I found an error...

**Comment by kolyshkin** [comment] 2021-11-11 23:02
OK, this is a systemd bug, the fix for which was just merged upstream (https://github.com/systemd/systemd/pull/21298). Coincidentally, I have developed a totally identical fix at about the same time. I have tested it on my machine by rebuilding systemd rpms with my patch added, and it fixes the issue.

Problem with the fix is, in my case, a mere `rpm -Uhv` of systemd rpms with the fix was not enough for the issue to go away -- a reboot was needed. I suspect the issue is systemd rpms postinstall scripts do re-exec of the main systemd process, but not per-user ones.

Having said that, if we do `dnf update` before we log in as `rootless` should fix the issue.

So, for now we have to wait for the appropriate Fedora bug (https://bugzilla.redhat.com/show_bug.cgi?id=2022041) to be fixed, and when our CI will be back to normal.

Alternatively, we can go back to F34 for the time being.

It's also possible to add rebuild of systemd to the process but that takes 20 minutes on my machine...

**Comment by ojab** [comment] 2021-11-11 23:34
or systemd-249.4-2.fc35 could be installed instead of using latest/broken version

**Comment by kolyshkin** [comment] 2021-11-11 23:35
Yes, downgrade is possible. Let me try that

**Comment by kolyshkin** [comment] 2021-11-11 23:47
Or we can use a scratch build once it's available from https://src.fedoraproject.org/rpms/systemd/pull-request/66

**Closed** 2021-11-12 03:51 UTC
Labels: kind/bug, area/cgroupv2, area/ci, area/rootless, area/systemd
