### ISSUE TITLE
runc update not having correct cgroup path

### ISSUE THREAD

**Issue by crosbymichael** [opencontainers/runc#1031] opened 2016-09-09 21:12 UTC
``` 
sudo runc update --memory 20m test
failed to write 20971520 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/user.slice/memory.limit_in_bytes: device or resource busy
michael|/containers/redis > sudo runc state test
{
  "ociVersion": "1.0.0-rc1",
  "id": "test",
  "pid": 2328,
  "bundlePath": "/containers/redis",
  "rootfsPath": "/containers/redis/samba",
  "status": "running",
  "created": "2016-09-09T21:10:02.678528834Z",
  "annotations": {
    "test": "test"
  }
}michael|/containers/redis > cat /proc/2328/cgroup 
11:freezer:/test
10:perf_event:/test
9:memory:/user.slice/test
8:hugetlb:/test
7:net_cls,net_prio:/test
6:blkio:/user.slice/test
5:pids:/user.slice/user-1000.slice/test
4:devices:/user.slice/test
3:cpu,cpuacct:/user.slice/test
2:cpuset:/test
1:name=systemd:/user.slice/user-1000.slice/session-c2.scope/test
michael|/containers/redis > 
```

If you look at the error message path it should be `9:memory:/user.slice/test` but its `/sys/fs/cgroup/memory/user.slice/memory.limit_in_bytes`.  Its missing the container name in the cgroiup path.

**Comment by rajasec** [comment] 2016-09-11 10:50
@crosbymichael @hqhq 
When I reverted the #1009 changes, runc update started working.
Looks like the problem is around c.Path where it got empty string

**Comment by cyphar** [comment] 2016-09-11 11:19
@rajasec `c.Path = ""` is acting correctly during joining, but I think that the issue is with `m.Paths` (when we figure out what the cgroup paths of a container are).

**Comment by rajasec** [comment] 2016-09-11 17:40
@cyphar 
Looks m.Paths is correct at least I have checked inside (m *Manager) Freeze(state configs.FreezerState)

**Comment by rajasec** [comment] 2016-09-11 18:46
with my understanding, we are trying to get the cgroup of container using the below  ( even for pause/update...)
since c.Path is NULL, we are having wrong cgroup path name.
        
cgPath := libcontainerUtils.CleanPath(c.Path)
        cgParent := libcontainerUtils.CleanPath(c.Parent)
        cgName := libcontainerUtils.CleanPath(c.Name)

**Closed** 2016-09-12 21:03 UTC
Labels: bug
