### ISSUE TITLE
leakage of cgroupv2

### ISSUE THREAD

**Issue by lifubang** [opencontainers/runc#2321] opened 2020-04-17 08:13 UTC
Nowadays, the upstream of container runtime, such as docker, containerd and podman, don't join cgroup namespace by default. If we use cgroup v2, we can view the host's whole cgroup fs structure in the container.

How to reproduce:
1. use podman:
```
[root@bogon runctest]# podman --runtime runc run --rm -it busybox ls /sys/fs/cgroup
cgroup.controllers      cgroup.stat             cpuset.cpus.effective   io.pressure             sys
cgroup.max.depth        cgroup.subtree_control  cpuset.mems.effective   machine.slice           system.slice
cgroup.max.descendants  cgroup.threads          docker                  memory.pressure         user.slice
cgroup.procs            cpu.pressure            init.scope              runctest
[root@bogon runctest]# podman --runtime runc run --rm -it busybox ls /sys/fs/cgroup/machine.slice
cgroup.controllers                                                             libpod-207bddd76f2fb04a53cc2778613cf11967141615fe42c39941ddcb9878c00e57.scope
cgroup.events                                                                  libpod-6353fec0668b6154ba3d5c82aca31f3728e03038e59dcc1f9d197225105811fd.scope
cgroup.freeze                                                                  libpod-80f3340e25a1ea18d7d4f3d2016f64a3763dba10c8a9c2b5e855a03dd4d1550b.scope
cgroup.max.depth                                                               memory.current
cgroup.max.descendants                                                         memory.events
cgroup.procs                                                                   memory.events.local
cgroup.stat                                                                    memory.high
cgroup.subtree_control                                                         memory.low
cgroup.threads                                                                 memory.max
cgroup.type                                                                    memory.min
cpu.max                                                                        memory.oom.group
cpu.pressure                                                                   memory.pressure
cpu.stat                                                                       memory.stat
cpu.weight                                                                     memory.swap.current
cpu.weight.nice                                                                memory.swap.events
io.bfq.weight                                                                  memory.swap.max
io.latency                                                                     pids.current
io.max                                                                         pids.events
io.pressure                                                                    pids.max
io.stat
```
2. use runc:
```
[root@bogon runctest]# runc run -d test
root@bogon runctest]# runc exec -t test ls /sys/fs/cgroup
cgroup.controllers      cpu.pressure            memory.pressure
cgroup.max.depth        cpuset.cpus.effective   runctest
cgroup.max.descendants  cpuset.mems.effective   sys
cgroup.procs            docker                  system.slice
cgroup.stat             init.scope              user.slice
cgroup.subtree_control  io.pressure
cgroup.threads          machine.slice
```

So, if the upstream want to support cgroup v2, we need to force join cgroup namespace.
Further more, shall we need to consider force join cgroup namespace in `runc`?

**Comment by lifubang** [comment] 2020-04-17 12:27
crun also have this problem:
```
[root@bogon runctest]# podman --runtime crun run --rm -it busybox ls /sys/fs/cgroup/machine.slice
cgroup.controllers                                                             libpod-6353fec0668b6154ba3d5c82aca31f3728e03038e59dcc1f9d197225105811fd.scope
cgroup.events                                                                  libpod-74ee28c9390d78cd690a4189f2f0fb74319af5628c432d18da1347305d9b98e2.scope
cgroup.freeze                                                                  libpod-80f3340e25a1ea18d7d4f3d2016f64a3763dba10c8a9c2b5e855a03dd4d1550b.scope
cgroup.max.depth                                                               memory.current
cgroup.max.descendants                                                         memory.events
cgroup.procs                                                                   memory.events.local
cgroup.stat                                                                    memory.high
cgroup.subtree_control                                                         memory.low
cgroup.threads                                                                 memory.max
cgroup.type                                                                    memory.min
cpu.max                                                                        memory.oom.group
cpu.pressure                                                                   memory.pressure
cpu.stat                                                                       memory.stat
cpu.weight                                                                     memory.swap.current
cpu.weight.nice                                                                memory.swap.events
io.bfq.weight                                                                  memory.swap.max
io.latency                                                                     pids.current
io.max                                                                         pids.events
io.pressure                                                                    pids.max
io.stat
```

**Comment by AkihiroSuda** [comment] 2020-04-17 12:49
This is fixed on recent Podman which sets `--cgroupns=private` by default on cgroup v2 hosts.

**Comment by giuseppe** [comment] 2020-04-17 12:49
I think the issue is in the version of Podman you are using.  Podman by default uses a cgroup namespace on cgroup v2.

If you still have the same issue after you upgrade Podman, please follow up on the https://github.com/containers/libpod issues tracker.

**Comment by AkihiroSuda** [comment] 2020-04-17 12:49
Closing as this is not an issue on runc side.

**Closed by AkihiroSuda** 2020-04-17 12:49 UTC

**Comment by lifubang** [comment] 2020-04-17 13:41
> This is fixed on recent Podman which sets `--cgroupns=private` by default on cgroup v2 hosts.



> Closing as this is not an issue on runc side.

What exactly I meat is:
Do we need to join cgroup namespace by default on cgroup v2.
We can provide a flag to let user to cancel this default set, for example `--nocgroupns`.

**Comment by AkihiroSuda** [comment] 2020-04-17 13:43
> Do we need to join cgroup namespace by default on cgroup v2.

Yes on higher level runtimes side (Docker/Podman), no on runc side.

> We can provide a flag to let user to cancel this default set, for example --nocgroupns.

`podman (docker) run --cgroupns=host=
