### ISSUE TITLE
cannot suid root when run as non-root

### ISSUE THREAD

**Issue by Naitreey** [opencontainers/runc#705] opened 2016-03-29 09:08 UTC
Hi, I am trying to run python parser with `suid` bit set. The container filesystem is exported from ubuntu docker image.

Here is my python parser status:

```sh
mortal@runc:/$ ls -l /usr/bin/python3.4 
-rwsr-xr-x 2 root root 3709944 Oct 14 21:42 /usr/bin/python3.4
```
You can see it has suid bit set for root.

Here is my `config.json`:

```json
{
	"ociVersion": "0.4.0",
	"platform": {
		"os": "linux",
		"arch": "amd64"
	},
	"process": {
		"terminal": true,
		"user": {
            "uid": 1000,
            "gid": 1000
        },
		"args": [
			"bash"
		],
		"env": [
			"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"TERM=xterm"
		],
		"cwd": "/",
		"capabilities": [
			"CAP_AUDIT_WRITE",
			"CAP_KILL",
			"CAP_NET_BIND_SERVICE",
            "CAP_SYS_CHROOT",
            "CAP_SETUID",
            "CAP_SETGID"
		],
		"rlimits": [
			{
				"type": "RLIMIT_NOFILE",
				"hard": 1024,
				"soft": 1024
			}
		],
		"noNewPrivileges": true
	},
	"root": {
		"path": "rootfs",
		"readonly": true
	},
	"hostname": "runc",
	"mounts": [
		{
			"destination": "/proc",
			"type": "proc",
			"source": "proc"
		},
		{
			"destination": "/dev",
			"type": "tmpfs",
			"source": "tmpfs",
			"options": [
				"nosuid",
				"strictatime",
				"mode=755",
				"size=65536k"
			]
		},
		{
			"destination": "/dev/pts",
			"type": "devpts",
			"source": "devpts",
			"options": [
				"nosuid",
				"noexec",
				"newinstance",
				"ptmxmode=0666",
				"mode=0620",
				"gid=5"
			]
		},
		{
			"destination": "/dev/shm",
			"type": "tmpfs",
			"source": "shm",
			"options": [
				"nosuid",
				"noexec",
				"nodev",
				"mode=1777",
				"size=65536k"
			]
		},
		{
			"destination": "/dev/mqueue",
			"type": "mqueue",
			"source": "mqueue",
			"options": [
				"nosuid",
				"noexec",
				"nodev"
			]
		},
		{
			"destination": "/sys",
			"type": "sysfs",
			"source": "sysfs",
			"options": [
				"nosuid",
				"noexec",
				"nodev",
				"ro"
			]
		},
		{
			"destination": "/sys/fs/cgroup",
			"type": "cgroup",
			"source": "cgroup",
			"options": [
				"suid",
				"noexec",
				"nodev",
				"relatime"
			]
		}
	],
	"hooks": {},
	"linux": {
		"resources": {
			"devices": [
				{
					"allow": false,
					"access": "rwm"
				}
			]
		},
		"namespaces": [
			{
				"type": "pid"
			},
			{
				"type": "network"
			},
			{
				"type": "ipc"
			},
			{
				"type": "uts"
			},
			{
				"type": "mount"
			}
		],
		"devices": null
	}
}
```

After entering the container with `runc start ubuntu`, I ran python with `/usr/bin/python3.4`. Using `os` module I can see both my current uid and euid are 1000, however I was expecting euid to be 0:

```python
mortal@runc:/$ /usr/bin/python3.4
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getuid()
1000
>>> os.geteuid()
1000
>>> 
```

**Comment by Naitreey** [comment] 2016-03-29 09:39
Version info:
```
runc version 0.0.9
spec version 0.4.0
```

**Comment by mikebrow** [comment] 2016-03-29 14:15
sudo chmod +s /usr/bin/python3.4

**Comment by Naitreey** [comment] 2016-03-29 14:23
Hi @mikebrow , I think I have done that, as you can obviously observed from the first cmdline listing I provided.

Actually, I can suid-root with runc 0.0.5, but not with runc 0.0.9.

**Comment by mikebrow** [comment] 2016-03-29 14:29
Hey.. did you try to set chmod +s?   Here's the before and after:

Before:
```
mike@mike-VirtualBox:~/go/src/github.com/busyboxtest2$ ls -l /usr/bin/python3.4
-rwxr-xr-x 1 root root 4144056 Oct 14 13:30 /usr/bin/python3.4
mike@mike-VirtualBox:~/go/src/github.com/busyboxtest2$ /usr/bin/python3.4
Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getuid()
1000
>>> os.geteuid()
1000
```
After:
```
mike@mike-VirtualBox:~/go/src/github.com/busyboxtest2$ sudo chmod +s /usr/bin/python3.4
mike@mike-VirtualBox:~/go/src/github.com/busyboxtest2$ ls -l /usr/bin/python3.4-rwsr-sr-x 1 root root 4144056 Oct 14 13:30 /usr/bin/python3.4
mike@mike-VirtualBox:~/go/src/github.com/busyboxtest2$ /usr/bin/python3.4Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getuid()
1000
>>> os.geteuid()
0
```

**Comment by cyphar** [comment] 2016-03-29 14:34
@Naitreey How did you extract the `rootfs`. If you used `docker export`, you need to make sure that you do `sudo tar xvf` when extracting (otherwise all of the files will be owned by your current user). I just ran the following commands and I can't reproduce this:

```
% docker start --name test ubuntu:14.04 sh
% docker export test > rootfs.tar
% mkdir rootfs
% sudo tar xvfC rootfs.tar rootfs/
# snip
% sudo chmod u+s rootfs/usr/bin/python3.4
% ls -la rootfs/usr/bin/python3.4
-rwsr-xr-x 2 root root 3709944 Oct 15 08:42 rootfs/usr/bin/python3.4
% runc spec
% # add CAP_SETUID and CAP_SETGID
% sudo runc start test
# python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getuid()
0
>>> os.getgid()
0
```

**Comment by cyphar** [comment] 2016-03-29 14:52
Okay, I just noticed something odd:

```
$ ls -la /usr/bin/python3.4
-rwsr-xr-x 1 root root 3709944 Oct 14 21:42 /usr/bin/python3.4
$ python3 
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.geteuid()
1000
>>> os.getegid()
0
>>> 
```

**Comment by mikebrow** [comment] 2016-03-29 15:11
Yeah reproduced here too.. also get another issue on ubuntu latest:
mike@mike-VirtualBox:~/go/src/github.com/ubuntutest$ sudo runc start test
groups: cannot find name for group ID 1000
I have no name!@runc:/$

**Comment by Naitreey** [comment] 2016-03-29 16:06
@mikebrow maybe that's because your `/etc/passwd` and `/etc/group` files do not contain entries for the corresponding uid/gid (namely 1000).

**Comment by mikebrow** [comment] 2016-03-29 16:27
you picked it... don't know why I expected those to move over automatically :-)

**Comment by Naitreey** [comment] 2016-03-30 09:24
Hi @cyphar , do you have any progress on the issue?

**Comment by cyphar** [comment] 2016-03-30 10:13
No. You reported it yesterday and I live in Australia.

**Comment by slayercat** [comment] 2016-03-30 12:50
in runc version 0.0.6, when execute a executable file with suid, kernel function
```
bprm_fill_uid(fs/exec.c)
```
will return successfully. while in runc version 0.0.9, it will return at 
```
if (task_no_new_privs(current))
```
still digging why.

**Comment by cyphar** [comment] 2016-03-30 13:02
@slayercat Ah, it might be because we added the `no_new_privs` bit at some point. This bit essentially disables stuff like `setuid` or `setcap` (and a bunch of other things) with `execve`. I vaguely remember some discussions about it a few months ago...

**Comment by slayercat** [comment] 2016-03-30 13:04
hi, @cyphar ,any plan about that?

**Comment by cyphar** [comment] 2016-03-30 13:04
@Naitreey Okay, I've found it. There's an option in `config.json` called `noNewPrivilieges` which is **`true` in the default config**. You need to set it to false.

```
...
"noNewPrivileges": false
...
```

**Comment by slayercat** [comment] 2016-03-30 13:07
thanks,it worked !

**Comment by Naitreey** [comment] 2016-03-30 13:10
Thanks for helping :+1:

**Comment by cyphar** [comment] 2016-03-30 14:13
@Naitreey If that fixes your problem, feel free to close this issue. :smile_cat:

**Closed** 2016-03-30 14:41 UTC
