### ISSUE TITLE
Libcontainer - GetPids retuns error

### ISSUE THREAD

**Issue by diptanu** [opencontainers/runc#602] opened 2016-03-01 01:10 UTC
The API manager.GetPids is returning an error `/sys/fs/cgroup/devices/user/1000.user/c1.session/55f75212-3dc8-36c2-9c4c-f997ed8d44c6/55f75212-3dc8-36c2-9c4c-f997ed8d44c6/cgroup.procs: no such file or directory` Looks like libcontainer is adding the name of the cgroup twice which creating the path to the `cgoup.procs` file.

**Comment by hqhq** [comment] 2016-03-01 08:05
Can you demonstrate how to reproduce this? `docker top` will call `manager.GetPids`, and I can't reproduce this with systemd cgroup driver.

**Comment by diptanu** [comment] 2016-03-01 15:47
Here is a small snippet of code for reproducing this. Please let me know if I am using the APIs incorrectly.

```
package main

import (
	"fmt"

	cgroupFs "github.com/opencontainers/runc/libcontainer/cgroups/fs"
	cgroupConfig "github.com/opencontainers/runc/libcontainer/configs"
	"os"
)

func main() {
	groups := &cgroupConfig.Cgroup{}
	groups.Resources = &cgroupConfig.Resources{}
	groups.Name = "foo"
        groups.Resources.AllowAllDevices = true
        groups.Resources.Memory = int64(20 * 1024 * 1024)
	groups.Resources.MemorySwap = int64(-1)
        groups.Resources.CpuShares = int64(200)

	manager := &cgroupFs.Manager{Cgroups: groups}
	manager.Apply(os.Getpid())

	p, err := manager.GetAllPids()
	fmt.Printf("PIDS %#v", p)
}
```

**Comment by diptanu** [comment] 2016-03-01 18:40
@mikebrow Yeah I am using master. And you will see the error if you use ```manager.GetPids```, ```manager.GetAllPids``` just returns an empty array.

This is on a Ubuntu 14.04 and doesn't have systemd, so libcontainer is using raw cgroup fs.

**Comment by mikebrow** [comment] 2016-03-01 19:00
Ok I can only reproduce this with an invalid group name.

go run test.go (with a valid group name)
GetPids: []int{8123, 8356}GetAllPids: []int{8123, 8356}
In the above example I ran your test with "box1" as the group name where the container id was box1.

go run test.go (with an invald group name for example set to "foo" when the container is is "box1")
GetPids error: open /sys/fs/cgroup/devices/user.slice/user-1000.slice/session-c2.scope/foo/foo/cgroup.procs: no such file or directoryGetPids: []int(nil)GetAllPids: []int(nil)

**Comment by diptanu** [comment] 2016-03-01 19:13
@mikebrow Ok, I see. So I am not setting the container ID anywhere. How do you know or set the Container ID?

**Comment by mikebrow** [comment] 2016-03-01 19:33
Well if you are using runc... see runc start --help for usage creating a container and  runc list to get the ids of the containers created through runc...  

If you are coding up your own version of runc.. you could start with runc/start.go and trace the code steps implemented by runc.

The container id is is a new mandatory argument to runc start, pause, exec, etc...

**Comment by diptanu** [comment] 2016-03-01 19:42
No I am not using runc, I just want to use libcontainer to create a cgroup and apply a pid to it.

**Comment by mikebrow** [comment] 2016-03-01 19:54
ok.. you could take a look at the code for runc start (create the cgroup) and runc exec (apply a pid to it) and filter it down to your specific use case.

**Comment by hqhq** [comment] 2016-03-02 09:28
I can confirm it's a bug in libcontainer. Now we use `func (raw *cgroupData) path(subsystem string) (string, error)` to get the cgroup path, the problem is in the case that `cgroupData.innerPath` is not absolute, like case in this PR, which only set `cgroup.Name`, after process join into cgroup, `d.path(subsystem)` will return a wrong path. Because we call `cgroups.GetThisCgroupDir(subsystem)` in `parentPath()` and the returned value is not expected because this process is already in the cgroup.

We can avoid calling `d.path()` after `Apply` to fix this, but it doesn't fix the root cause. @LK4D4 any thoughts on this?

**Comment by diptanu** [comment] 2016-03-02 19:15
@hqhq @LK4D4  I have a workaround for the time being. Not setting the ```Name``` but setting the ```Path``` works. And I am getting the ```Path``` by calling the API ```cgroups.GetThisCgroupDir("devices")```

**Comment by diptanu** [comment] 2016-03-18 22:28
@hqhq @LK4D4 Any updates on this?

**Comment by mikebrow** [comment] 2016-03-18 23:00
I may be confused about what you're trying to do so pls correct if I'm wrong.  Beyond the internal issue regarding the repetitive path name, your use of a non-existent group name "foo" is the only thing stopping you from moving forward.  As shown above using an existing group name works just fine with your code. The group name is set by the user / program creating the container.  Your using "foo" does not work because there is no container named "foo."

step 1 start a container with a container id of "foo"
step 2 run your sample code to get a list of process in the container "foo"  

Your code is doing step 2 but there is no container named foo to attach to, thus the failure.

**Comment by diptanu** [comment] 2016-03-19 01:07
@mikebrow I am not creating a container using cgroup, just creating a cgroup using libcontainer. The problem is if I set `group.Name` then the path names become repetitive. So I am setting the Path and not the name in the cgroup while creating it.

**Comment by mikebrow** [comment] 2016-03-19 04:54
Maybe catch us up on chat sometime.. I thought the problem was get pids was returning an error for an existing container's cgroup. Not that you were trying to create a cgroup with no containers.

**Comment by cyphar** [comment] 2017-03-07 07:24
This hasn't had any activity in the past year, so I'm closing this issue. If you're still having issues using `libcontainer/cgroup` please feel free to create a new issue or reopen this one with an update.

**Closed by cyphar** 2017-03-07 07:24 UTC
