### ISSUE TITLE
Error loading seccomp filter into kernel: invalid argument 

### ISSUE THREAD

**Issue by yanc0** [opencontainers/runc#374] opened 2015-10-27 20:25 UTC
Hi,
I compile runc on Debian Stretch ARM (scaleway server) and I can't launch a container because of a seccomp fail.

```
$ sudo runc start
error loading seccomp filter into kernel: invalid argument
WARN[0000] exit status 1                                
FATA[0000] Container start failed: [8] System error: error loading seccomp filter into kernel: invalid argument 

$ uname -a
Linux sudomakeinstall-me 4.1.6-249 #1 SMP Mon Aug 31 12:34:47 UTC 2015 armv7l GNU/Linux

$ go version
go version go1.4.3 linux/arm
```

libseccomp2 for armhf is installed with version 2.2.3-2 and the seccomp config are 

```
        "apparmorProfile": "",
        "selinuxProcessLabel": "",
        "seccomp": {
            "defaultAction": "SCMP_ACT_ALLOW",
            "architectures": null,
            "syscalls": []
        },
```

**Comment by yanc0** [comment] 2015-10-28 09:47
I compiled runc with freshly builded linux/arm version of go 1.5.1. I also regenerate `runc spec` to have fresh configs but I always get the same error. How can I provide more information to this thread to be as exhaustive as I can?

Thanks !

**Comment by yanc0** [comment] 2015-10-28 10:43
I found a workaround for testing purpose only on ARM Scalway servers. You have to compile runc with apparmor support. This hack disable seccomp so it is not a great solution but you can play with runc.

Modify `Makefile` with:
```
BUILDTAGS=apparmor
```
After compiled, generate specs with `runc spec` and remove seccomp configurations to have this:
```
		"apparmorProfile": "",
		"selinuxProcessLabel": "",
		"rootfsPropagation": ""
```
After that, you can `sudo runc start` in your container directory

**Comment by rakyll** [comment] 2016-02-04 21:29
I can reproduce the same issue on Raspbian on a Raspberry Pi 2.

**Comment by crosbymichael** [comment] 2016-02-05 02:01
Maybe you have to edit the "architectures" field in the seccomp section to add the armf arches?  I dont have an ARM system around to test but maybe @mheon knows?

**Comment by justincormack** [comment] 2016-04-28 15:21
Does your kernel have seccomp support enabled? Many arm distros do not, because the kernel support is only recent.

**Comment by cyphar** [comment] 2017-03-06 08:38
Since this hasn't had any activity for nearly a year, I'm going to close this. @yanc0 feel free to reopen this if it is still an issue (though as Justin said the issue might be that your kernel doesn't support seccomp).

**Closed by cyphar** 2017-03-06 08:38 UTC
