### ISSUE TITLE
1.0.0-rc5 breaks rootless container example in README

### ISSUE THREAD

**Issue by sunaku** [opencontainers/runc#1801] opened 2018-05-10 17:49 UTC
Hello,

The 1.0.0-rc5 release breaks the "Rootless containers" example in the README, where it fails with a "mountpoint for cgroup not found" error.  This issue doesn't occur under the previous 1.0.0-rc4 release.

Thanks for your consideration.

# Broken under 1.0.0-rc5 💥 

```sh
$ /opt/runc-1.0.0-rc5/sbin/runc --root /tmp/runc run mycontainerid-rc5
container_linux.go:348: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"mountpoint for cgroup not found\""
```

# Working under 1.0.0-rc4 👌 

```sh
$ /opt/runc-1.0.0-rc4/bin/runc --root /tmp/runc run mycontainerid-rc4
/ # ls
bin    dev    etc    home   lib64  proc   root   sbin   sys    tmp    usr    var
```

# Same config used in both

```sh
$ /opt/runc-1.0.0-rc5/sbin/runc spec --rootless
$ cat config.json
{
        "ociVersion": "1.0.0",
        "process": {
                "terminal": true,
                "user": {
                        "uid": 0,
                        "gid": 0
                },
                "args": [
                        "sh"
                ],
                "env": [
                        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                        "TERM=xterm"
                ],
                "cwd": "/",
                "capabilities": {
                        "bounding": [
                                "CAP_AUDIT_WRITE",
                                "CAP_KILL",
                                "CAP_NET_BIND_SERVICE"
                        ],
                        "effective": [
                                "CAP_AUDIT_WRITE",
                                "CAP_KILL",
                                "CAP_NET_BIND_SERVICE"
                        ],
                        "inheritable": [
                                "CAP_AUDIT_WRITE",
                                "CAP_KILL",
                                "CAP_NET_BIND_SERVICE"
                        ],
                        "permitted": [
                                "CAP_AUDIT_WRITE",
                                "CAP_KILL",
                                "CAP_NET_BIND_SERVICE"
                        ],
                        "ambient": [
                                "CAP_AUDIT_WRITE",
                                "CAP_KILL",
                                "CAP_NET_BIND_SERVICE"
                        ]
                },
                "rlimits": [
                        {
                                "type": "RLIMIT_NOFILE",
                                "hard": 1024,
                                "soft": 1024
                        }
                ],
                "noNewPrivileges": true
        },
        "root": {
                "path": "rootfs",
                "readonly": true
        },
        "hostname": "runc",
        "mounts": [
                {
                        "destination": "/proc",
                        "type": "proc",
                        "source": "proc"
                },
                {
                        "destination": "/dev",
                        "type": "tmpfs",
                        "source": "tmpfs",
                        "options": [
                                "nosuid",
                                "strictatime",
                                "mode=755",
                                "size=65536k"
                        ]
                },
                {
                        "destination": "/dev/pts",
                        "type": "devpts",
                        "source": "devpts",
                        "options": [
                                "nosuid",
                                "noexec",
                                "newinstance",
                                "ptmxmode=0666",
                                "mode=0620"
                        ]
                },
                {
                        "destination": "/dev/shm",
                        "type": "tmpfs",
                        "source": "shm",
                        "options": [
                                "nosuid",
                                "noexec",
                                "nodev",
                                "mode=1777",
                                "size=65536k"
                        ]
                },
                {
                        "destination": "/dev/mqueue",
                        "type": "mqueue",
                        "source": "mqueue",
                        "options": [
                                "nosuid",
                                "noexec",
                                "nodev"
                        ]
                },
                {
                        "destination": "/sys",
                        "type": "none",
                        "source": "/sys",
                        "options": [
                                "rbind",
                                "nosuid",
                                "noexec",
                                "nodev",
                                "ro"
                        ]
                }
        ],
        "linux": {
                "uidMappings": [
                        {
                                "hostID": 1009,
                                "containerID": 0,
                                "size": 1
                        }
                ],
                "gidMappings": [
                        {
                                "hostID": 1009,
                                "containerID": 0,
                                "size": 1
                        }
                ],
                "namespaces": [
                        {
                                "type": "pid"
                        },
                        {
                                "type": "ipc"
                        },
                        {
                                "type": "uts"
                        },
                        {
                                "type": "mount"
                        },
                        {
                                "type": "user"
                        }
                ],
                "maskedPaths": [
                        "/proc/kcore",
                        "/proc/latency_stats",
                        "/proc/timer_list",
                        "/proc/timer_stats",
                        "/proc/sched_debug",
                        "/sys/firmware",
                        "/proc/scsi"
                ],
                "readonlyPaths": [
                        "/proc/asound",
                        "/proc/bus",
                        "/proc/fs",
                        "/proc/irq",
                        "/proc/sys",
                        "/proc/sysrq-trigger"
                ]
        }
}
```

**Comment by cyphar** [comment] 2018-05-12 03:52
Yeah, this is a regression caused by #1540 -- we should not attempt to apply cgroup limits if we don't have a cgroup mount (with the note that if the limits are set we have to fail).

**Comment by sunaku** [comment] 2018-05-14 20:55
I have built runc at commit ff4481dbf63b88fdccdb0e7ac1ceadd2b18420c7 where #1540 was merged, but it doesn't seem to have solved the problem: I'm still getting the same error (I'm running `runc` directly from the build directory without `make install`). 😱 Are you able to reproduce this observation? Thanks.

**Comment by cyphar** [comment] 2018-05-15 04:32
@sunaku I said that it was *caused* by #1540, so you should test with 0eafdc33825ce705fdc73213dbcd1f6510b60f46 (before it was merged) not ff4481dbf63b88fdccdb0e7ac1ceadd2b18420c7 (after it was merged).

As for reproducing, I cannot reproduce it if you create a new `config.json` with `runc spec --rootless` (from memory #1540 included changes to the cgroup generation which fixed this problem implicitly -- that's why our integration tests still pass). But I have very little doubt that it's caused by #1540 -- because before that commit cgroups were basically ignored in rootless mode.

**Comment by sunaku** [comment] 2018-05-15 18:40
Thanks @cyphar! 😅 Sorry I completely missed the detail about _causation_ in your message. 😅😅😅

I have rebuilt from 0eafdc33825ce705fdc73213dbcd1f6510b60f46 and observed the problem is gone (but I still get an error: just a different one).

```sh
$ ./src/github.com/opencontainers/runc/runc --root /tmp/runc run mycontainerid-dev
container_linux.go:295: starting container process caused "process_linux.go:302: running exec setns process for init caused \"exit status 127\""
```

Same thing happened after regenerating the rootless config file as you suggested.  Not much changed:

```diff 
diff --git a/config.json b/config.json.rc5
index 8e4c0e0..6da448a 100644
--- a/config.json
+++ b/config.json.rc5
@@ -157,7 +157,8 @@
                        "/proc/timer_list",
                        "/proc/timer_stats",
                        "/proc/sched_debug",
-                       "/sys/firmware"
+                       "/sys/firmware",
+                       "/proc/scsi"
                ],
                "readonlyPaths": [
                        "/proc/asound",
```

Finally, my main concern is whether the original problem I've reported in this issue is on the roadmap for 1.0.0?  Because I'm currently using 1.0.0-rc4 and don't want to be stranded 😱 in terms of future mobility.

Thanks for your consideration.

**Comment by cyphar** [comment] 2018-05-16 04:21
> ```
> $ ./src/github.com/opencontainers/runc/runc --root /tmp/runc run mycontainerid-dev
> container_linux.go:295: starting container process caused "process_linux.go:302: running exec setns process for init caused \"exit status 127\"
> ```

Huh, that's very strange. I've not seen that before (we use exit codes for debugging in `nsexec.c` for various quite horrible historical reasons), but that error code looks like something `abort()`ed or there was some other program death that shouldn't have happened...

> my main concern is whether the original problem I've reported in this issue is on the roadmap for 1.0.0?

Yeah, I'll tag it as 1.0.0 (though of course it should be noted we've been slowly pushing back the deadline for 1.0.0 for several months -- I wouldn't worry too much).

**Comment by sunaku** [comment] 2018-05-18 04:04
Thanks @cyphar! Yes, the output I provided is from the same machine I've tested 1.0.0-rc4 successfully on.

**Comment by cyphar** [comment] 2018-11-14 11:42
Sorry that I haven't touched this in a while. Is this is still a problem (we fixed a bunch of regressions recently related to rootless containers)? We are currently in release-crunch mode and so if it isn't already fixed it will likely have to wait until post-1.0.

Please note that we are planning on a maximum of 2-month cadence of releases. So fixes will be in releases with far more regularity.

**Comment by kolyshkin** [comment] 2021-06-11 19:53
@AkihiroSuda PTAL (this should probably be closed)

**Comment by AkihiroSuda** [comment] 2021-06-11 19:57
Yes, rc4/rc5 is quite old, we no longer need to care about rc4 compatibility.

**Closed by AkihiroSuda** 2021-06-11 19:57 UTC
Labels: area/rootless
