### ISSUE TITLE
cgroup/systemd func systemdProperties sets wrong char entry.Path

### ISSUE THREAD

**Issue by yangfeiyu20102011** [opencontainers/runc#3567] opened 2022-08-23 07:55 UTC
```
case devices.CharDevice: 
entry.Path = fmt.Sprintf("/dev/char/%d:%d", rule.Major, rule.Minor)
```
This may set wrong char entry.Path when comes with NVIDIA devices, and it will set 
`DeviceAllow=/dev/char/195:0 rw` in systemd DeviceAllow.conf. It will not work.

**Comment by yangfeiyu20102011** [comment] 2022-08-23 07:58
https://github.com/opencontainers/runc/pull/3568 will fix it.

**Comment by yangfeiyu20102011** [comment] 2022-08-23 08:00
@kolyshkin PTAL, thanks!

**Comment by kolyshkin** [comment] 2023-04-26 01:35
Duplicate of #3671

**Comment by kolyshkin** [comment] 2023-04-26 01:38
OK this is not a duplicate but a different issue.

This was fixed in system v240, if you're using an earlier version, there is nothing you can do about it.

I also heard that nvidia is going to fix it in their drivers, so that the proper /dev/... nodes will be created (which will help with older systemd).

**Comment by kolyshkin** [comment] 2023-04-26 01:40
For some details about why systemd v240 is needed, see the description of https://github.com/opencontainers/runc/pull/3842

So, there's nothing we can do when older systemd is used, and in case systemd is >= v240, you either need runc < 1.1.3 or >= 1.1.7 (not yet released), or the one built from the main branch (after merging https://github.com/opencontainers/runc/pull/3842).

**Closed by kolyshkin** 2023-04-26 01:40 UTC
