### ISSUE TITLE
Cannot start container: no space left on device (cpuset cgroup)

### ISSUE THREAD

**Issue by iaguis** [opencontainers/runc#133] opened 2015-07-16 16:53 UTC
I was occasionally getting this error when running docker:

```
> docker run --rm -ti busybox
Error response from daemon: Cannot start container ca65deb2d7972d5a1772023ad82d843bb639fcfea9d75e78e0f99fcad9e683ba: [8] System error: write /sys/fs/cgroup/cpuset/system.slice/docker-ca65deb2d7972d5a1772023ad82d843bb639fcfea9d75e78e0f99fcad9e683ba.scope/cgroup.procs: no space left on device
```

After investigating a bit I found the cause of the problem.

I get this error because `cpuset.mems` in the container's cpuset cgroup directory is empty. In that case, libcontainer [sets that file to the value of the parent](https://github.com/docker/libcontainer/blob/83a102cc68a09d890cce3b6c2e5c14c49e6373a0/cgroups/fs/cpuset.go#L106) and does this recursively until it finds an existing parent.

An example might be easier to understand, if the container's cpuset cgroup directory is

```
/sys/fs/cgroup/cpuset/system.slice/docker-ca65deb2d7972d5a1772023ad82d843bb639fcfea9d75e78e0f99fcad9e683ba.scope
```

and the current existing directories are

```
/sys/fs/cgroup/cpuset/
```

libcontainer will start at `docker-ca65deb2d7972d5a1772023ad82d843bb639fcfea9d75e78e0f99fcad9e683ba.scope`, go to the parent and then go one more level up to `cpuset` because `system.slice` doesn't exist. Then it will set `/sys/fs/cgroup/cpuset/system.slice/cpuset.mems` to the value in `/sys/fs/cgroup/cpuset/cpuset.mems` and `/sys/fs/cgroup/cpuset/system.slice/docker-ca65deb2d7972d5a1772023ad82d843bb639fcfea9d75e78e0f99fcad9e683ba.scope/cpuset.mems` to that same value.

This works fine when `/sys/fs/cgroup/system.slice` doesn't exist. But if it exists and has an empty value, `/sys/fs/cgroup/cpuset/system.slice/docker-ca65deb2d7972d5a1772023ad82d843bb639fcfea9d75e78e0f99fcad9e683ba.scope/cpuset.mems` will also end up with an empty value, causing the error.

The solution could be keeping the recursion until you find the first non-empty value or you're out of the cpuset controller.

/cc @crosbymichael @kayrus @alban

**Comment by alban** [comment] 2015-07-16 22:36
I have this issue as well. The workaround is to run the following command before starting a Docker container:

```
# echo 0 >  /sys/fs/cgroup/cpuset/system.slice/cpuset.mems
```

**Comment by hqhq** [comment] 2015-07-17 04:15
I think https://github.com/docker/libcontainer/pull/642 alread fixed it, you can try again after https://github.com/docker/docker/pull/14693 is merged.

**Comment by iaguis** [comment] 2015-07-17 08:20
Oh, I didn't see that PR. Pretty sure it fixes the problem. I'll try again when libcontainer is updated and reopen if I still have problems.

Thanks!

**Comment by pbx0** [comment] 2015-08-04 20:38
In the process of testing a backport of https://github.com/docker/libcontainer/pull/642 into docker 1.7.1 it seems the problem is not fully solved for me.

If I reproduce the issue with a version of docker that includes the fix, docker will produce the same error. If I run docker again, the issue is then resolved until the next restart of the machine.

I've found that both 1.7.1 (with backported fix) and 1.8.0-rc1 will behave identically in this regard.

**Comment by alban** [comment] 2015-08-06 14:26
http://permalink.gmane.org/gmane.linux.kernel.cgroups/13990

**Comment by carlosfunk** [comment] 2015-09-02 03:09
A `boot2docker upgrade` fixed this for me by upgrading me to v1.8.1

**Comment by hqhq** [comment] 2015-09-07 02:26
@pbx0 Is this problem still existed? Can you show the steps how you reproduce the issue?

**Comment by hqhq** [comment] 2015-09-07 02:34
@alban 's patch did fix the kernel bug in 3.17+, @pbx0 if you are using kernel newer than 3.17, probably should merge that kernel fix and try again.

**Comment by pbx0** [comment] 2015-09-07 16:42
@hqhq I can confirm alban's kernel patch fixed it for me.  Forgot to come back here and say so.

**Comment by crosbymichael** [comment] 2015-09-14 22:10
I'll close this one since you reported back the kernel update fixed it for you.  Thanks!

**Closed by crosbymichael** 2015-09-14 22:10 UTC

**Comment by truebit** [comment] 2015-11-05 08:27
`echo 1 > /sys/fs/cgroup/docker/cgroup.clone_children` did the trick on Debian wheezy with kernel 3.16

**Comment by romuald** [comment] 2016-01-12 16:30
Unfortunately, problem is still present (Debian wheezy, kernel 3.16.0-0.bpo.4-amd64, Docker 1.9.1)

**Comment by valentinbud** [comment] 2016-01-17 13:23
@truebit in my case, Wheezy, kernel 3.16.0-0.bpo.4-amd64, Docker 1.9.1, just like @romuald's your fix doesn't do the trick. You're running Docker 1.8.3 though.

```bash
$ cat /sys/fs/cgroup/docker/cgroup.clone_children
1
```

I have stop/start docker and I am trying to run a (progrium/consul)[https://hub.docker.com/r/progrium/consul/] container fails with the following:

```bash
95003f34b7dba95e6dd63a96774ee3505027bb34529dfc7a22999b3d93c57779
Error response from daemon: Cannot start container 95003f34b7dba95e6dd63a96774ee3505027bb34529dfc7a22999b3d93c57779: [8] System error: write /sys/fs/cgroup/docker/95003f34b7dba95e6dd63a96774ee3505027bb34529dfc7a22999b3d93c57779/cgroup.procs: no space left on device
```

@romuald have you found any fix for this?

**Comment by valentinbud** [comment] 2016-01-17 13:36
There's something wrong with the node in question. On another Wheezy/Docker 1.9.1 works. My node needs a restart.

**Comment by kramach1980** [comment] 2016-07-19 23:04
I see this issue of cannot start containers on "3.19.0-25-generic".
Do we know if the patch is present in this kernel version? or it is only on 4.2 and mainline?

**Comment by stutefish** [comment] 2017-09-20 15:39
I still get this issue on ubuntu trusty 14.04/docker 17.07

**Comment by samskiter** [comment] 2022-08-17 13:52
Is this still an issue? I see a lot of commits above that mention fixing this issue
