### ISSUE TITLE
rc93 discussion (Feb 2021?)

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2659] opened 2020-10-23 05:06 UTC
I propose releasing rc93 in ~the next month~ December.

@opencontainers/runc-maintainers Please add items you want to get merged in rc93 to https://github.com/opencontainers/runc/milestone/10

Notable changes since rc92: https://github.com/opencontainers/runc/compare/v1.0.0-rc92...master
- support Cgroups.Resources.Unified without v1 conversion https://github.com/opencontainers/runc/commit/b006f4a18047f5815bb24db3a18b276018f9d0a1
- support CAP_PERFMON, CAP_BPF, and CAP_CHECKPOINT_RESTORE https://github.com/opencontainers/runc/commit/6dfbe9b80707b1ca188255e8def15263348e0f9a
- support Go 1.15 https://github.com/opencontainers/runc/commit/4c71a68c6e9c8f2081116f833b3a62868a45a062 , 1.16(rc1) https://github.com/opencontainers/runc/commit/b1195b7667fd9e13eb0a96fa1995b172b77e5a83
- Move cgroup v2 out of experimental https://github.com/opencontainers/runc/commit/3f2f06dfe1b3289b01daa531964b4f0af49cdf2d
- Removal of "apparmor" and "selinux" build tags. These features are now always compiled. https://github.com/opencontainers/runc/commit/552a1c7bb19da3cbce18f98da6bb8286a366d7e1 https://github.com/opencontainers/runc/commit/cb269306807dcfd7f742c8444aca2e638bd81550
- new blkio and cpuset stats https://github.com/opencontainers/runc/commit/990a6c57f1e23343400cdcaaf44ed654421a212d  https://github.com/opencontainers/runc/commit/ab27e12cebf148aa5d1ee3ad13d9fc7ae12bf0b6
- seccomp: prepend -ENOSYS stub to all filters https://github.com/opencontainers/runc/commit/7a8d7162f9d72f20d83eaa36aeb5426deecd58f2
- Lots of refactoring

**Comment by AkihiroSuda** [comment] 2020-10-28 06:10
@cyphar WDYT?

**Comment by cyphar** [comment] 2020-10-29 05:04
I don't have any outstanding things I'd like to get into rc93. I just merged #2634 so I guess the only thing left is whether we want to mark cgroupv2 as non-experimental. As far as I can tell, we still need to sort out #2602 / #2603 (so that `"unified"` works properly under systemd). I don't know how much remaining work there is to do to fix that.

All of that being said, I would hope we can do a 1.0 release a few weeks after rc93 (assuming nothing major happens). So any features we don't get in to rc93 will need to wait a month or so.

**Comment by dims** [comment] 2020-10-29 10:41
I would love to get `rc93` into containerd and then kubernetes when it's ready. Early November looks great for k8s at least as 1.20 code freeze is Nov 12-ish at the moment.

**Comment by kolyshkin** [comment] 2020-11-02 19:49
> (so that "unified" works properly under systemd)

I'm not sure this is super critical to have for rc93, but my WIP attempt is in https://github.com/opencontainers/runc/pull/2669, will try to add more this week

**Comment by AkihiroSuda** [comment] 2020-11-17 16:57
Do we want to wait for https://github.com/opencontainers/runc/pull/2599 (reduces reading mountinfo), or shall we release rc93 from the current master?

**Comment by cyphar** [comment] 2020-11-18 03:00
I'll review #2599 now, we can merge it now (assuming it's all good) and then I'll send out the vote for the release.

**Comment by AkihiroSuda** [comment] 2020-11-26 03:27
This is likely to be early next month, probably.

**Comment by cyphar** [comment] 2020-11-27 08:20
We probably want to hotfix #2151 in this release so Docker can at least check that our hotfix won't break them.

**Comment by AkihiroSuda** [comment] 2020-12-10 16:14
@cyphar What do we need for #2151? How long will it take?

**Comment by stokito** [comment] 2021-01-05 18:47
It would be nice to perform at least intermediate release because it's so many changes that github even can't show diff between master and last release tag.

**Comment by ehashman** [comment] 2021-01-11 17:12
Hi folks,

Any updates on this? It looks like some of the fixes since the previous release will be needed to address https://github.com/kubernetes/kubernetes/issues/97497

cc @AkihiroSuda @cyphar

**Comment by AkihiroSuda** [comment] 2021-01-12 03:25
@ehashman I think the current blocker is whether to include this to rc93 or not: https://github.com/opencontainers/runc/issues/2151

**Comment by kylecarbs** [comment] 2021-01-20 01:49
@cyphar any ideas on rc93 release date?

https://github.com/opencontainers/runc/pull/2522 is quite critical for us to use runc.

**Comment by AkihiroSuda** [comment] 2021-01-20 02:03
Soon after reaching the decision on https://github.com/opencontainers/runc/pull/2750 .
I personally expect it to land on Feb, but not certainty.

**Comment by cyphar** [comment] 2021-01-20 02:48
Yeah #2750 is the final blocker imho.

**Comment by kolyshkin** [comment] 2021-01-31 19:51
I have added https://github.com/opencontainers/runc/pull/2753 / https://github.com/opencontainers/runc/pull/2774 to the rc93 milestone as it's a regression that is seen in production and the fix makes sense.

**Comment by kolyshkin** [comment] 2021-01-31 19:58
I suggest we merge #2599 #2769 #2774 and bake a release.

**Comment by cyphar** [comment] 2021-02-01 00:03
Yup, I agree.

**Comment by cyphar** [comment] 2021-02-02 03:14
That's all of the PRs merged. Tip is still failing lints, but as discussed we can just move on with a release.

**Comment by dims** [comment] 2021-02-02 12:12
w00t! thanks @cyphar

**Closed** 2021-02-04 01:16 UTC
