### ISSUE TITLE
rootless runc exec causes panic: cannot statfs cgroup root (When /sys is not mounted)

### ISSUE THREAD

**Issue by coryb** [opencontainers/runc#2573] opened 2020-09-03 02:11 UTC
Seeing a panic from `runc exec` when run with rootlesskit.  

Here is the full stack, runc built from latest [master](https://github.com/opencontainers/runc/commit/09ddc63afdde16d5fb859a1d3ab010bd45f08497)
```
panic: cannot statfs cgroup root

goroutine 1 [running, locked to thread]:
github.com/opencontainers/runc/libcontainer/cgroups.IsCgroup2UnifiedMode.func1()
        /go/src/github.com/opencontainers/runc/libcontainer/cgroups/utils.go:45 +0xc5
sync.(*Once).doSlow(0x56030c2f2dd8, 0x56030c00ccc0)
        /usr/lib/go-1.15/src/sync/once.go:66 +0xee
sync.(*Once).Do(...)
        /usr/lib/go-1.15/src/sync/once.go:57
github.com/opencontainers/runc/libcontainer/cgroups.IsCgroup2UnifiedMode(0x20)
        /go/src/github.com/opencontainers/runc/libcontainer/cgroups/utils.go:42 +0x5a
github.com/opencontainers/runc/libcontainer.cgroupfs(0xc0001ae120, 0xc00000f000, 0x56030c021f00, 0x56030c29da60)
        /go/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:121 +0x28
github.com/opencontainers/runc/libcontainer.Cgroupfs(...)
        /go/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:134
github.com/opencontainers/runc/libcontainer.New(0x0, 0x0, 0x0, 0x0, 0x0, 0xc0001aad88, 0x56030c021f60, 0xc000253618, 0x0)
        /go/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:199 +0x165
main.glob..func6(0xc00012e840, 0x0, 0xc000059b60)
        /go/src/github.com/opencontainers/runc/init.go:42 +0x39
github.com/urfave/cli.HandleAction(0x56030bf6e900, 0x56030c00dd18, 0xc00012e840, 0xc00012e840, 0x0)
        /go/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:523 +0xfd
github.com/urfave/cli.Command.Run(0x56030bc94f87, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x56030bcb2599, 0x51, 0x0, ...)
        /go/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:174 +0x58e
github.com/urfave/cli.(*App).Run(0xc0001208c0, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:276 +0x7d4
main.main()
        /go/src/github.com/opencontainers/runc/main.go:151 +0xc6c
exec failed: container_linux.go:370: starting container process caused: read init-p: connection reset by peer
```

Currently seeing this via some work I am doing on buildkit, I have not tried to narrow it down outside of buildkit yet.

cc @AkihiroSuda

**Comment by AkihiroSuda** [comment] 2020-09-03 07:02
The cause is that BuildKit doesn't mount `/sys`: https://github.com/moby/buildkit/blob/3aa7902d40d8a7fe911ee35488985cb58a346710/util/rootless/specconv/specconv_linux.go#L29

https://github.com/moby/buildkit/pull/1627#discussion_r482745356

**Comment by cyphar** [comment] 2020-09-03 09:23
A panic is less than ideal, but runc cannot work without cgroupfs -- it would be unsafe to create containers without at least the devices cgroup.

**Comment by ashwani29** [comment] 2020-09-05 02:36
@AkihiroSuda I can't run commands with `sudo` prefix in the container. Does this mean, it is a rootless container?

**Comment by cyphar** [comment] 2020-09-05 04:33
@AkihiroSuda Ah sorry, I missed the mention of RootlessKit in the description.

**Comment by cyphar** [comment] 2020-09-05 04:37
@ashwani29 No. A rootless container is a container which is configured and created by an unprivileged user (in contrast to standard Docker-like setups where the whole thing is configured by a daemon that runs as root). The most likely reason why `sudo ...` isn't working in your container is that most containers don't include a `sudo` binary (the "sudo" package isn't usually installed for container images because it's a waste of space -- most containers don't need `sudo` anyway).

**Comment by ashwani29** [comment] 2020-09-05 06:04
@cyphar a process joins the container and has to edit the kernel files like `ns_last_pid`, This is giving error of `Read only file system` whereas with the same process I'm able to edit the host's `ns_last_pid` file. I'm guessing it's because the process isn't running as root in the container. How can I achieve this? 
and what complete binary should I install for a `runc` container such that it doesn't need to worry about all the packages like `sudo` or any compiler(like `g++`, `python`) required to compile and run different types of programs? I cannot install `sudo` with `apt get install` as then it throws an error for not founding `apt`.

**Comment by cyphar** [comment] 2020-09-05 10:26
Your questions aren't related to this issue, and you're basically asking for us to help you with checkpoint-restore/criu#1199. I posted a comment there, but I would really appreciate it if you'd stop commenting on unrelated issues with support questions (I believe this is at least the third time you've done this now).

**Comment by cyphar** [comment] 2020-10-29 05:00
#2634 was merged.

**Closed by cyphar** 2020-10-29 05:00 UTC
Labels: area/cgroupv1, area/cgroupv2, area/rootless, bug
