### ISSUE TITLE
How to run hybrid rootless container ? (create network and cgroups namespace with root right and start runc in rootless))

### ISSUE THREAD

**Issue by tangicolin** [opencontainers/runc#1397] opened 2017-04-05 16:43 UTC
My current understanding it is that cgroups namespace and network namespace require capablites so i can not be used in rootless mode. 

It is possible to have some preconfigured network namespace and cgroups namespace (so created with root user) and simply bind it when you run runC in rootless mode ? 

For the moment i block on the network namespace (i have not yet try to play with cgroups namespace binding). I create network namespace with the following script : 
https://gist.github.com/dpino/6c0dca1742093346461e11aa8f608a99

And i simply try to use the following network snippet in config.json : 
```
{
				"type": "network",
				"path": "/var/run/netns/ns1"
}

```

But i have the following error : 
`container_linux.go:262: starting container process caused "process_linux.go:247: running exec setns process for init caused \"exit status 16\""
` 

My runc version is 
```
runc version 1.0.0-rc3
commit: f990e58f26ab48367284f4a4e21bb95d641cde19
spec: 1.0.0-rc5

```

Do someone have already try this type of settings ? Does it is possible ? 

And does it is possible to run hook prestat of config.json in a another user ? (Idea here is to have prestat hook in root user and runc run in rootless mode).

**Comment by cyphar** [comment] 2017-04-05 16:56
> My current understanding it is that cgroups namespace and network namespace require capablites so i can not be used in rootless mode.

Minor nit: you can create both of those namespaces in a rootless container. The problem is that neither are useful for common usage (the network namespace doesn't have an interface to the host and the cgroup namespace scopes you to a cgroup that you don't control).

> For the moment i block on the network namespace (i have not yet try to play with cgroups namespace binding). I create network namespace with the following script :

Unfortunately joining isn't as simple as creating a new network namespace. You still need a `CAP_SYS_ADMIN` in the user namespace that the network namespace was created in in order to join the network namespace. There's also probably some `CAP_NET_ADMIN` requirements. If you wanted to do something hybrid here's how I would recommend it (and I imagine this is how Garden does it): Create an unprivileged network namespace within runC, then modify that network namespace from the host using your privileged process.

If you want advice on this topic, I'd ask the CloudFoundry developers who AFAIK have some networking support in CloudFoundry for rootless containers.

**Comment by tangicolin** [comment] 2017-04-07 09:32
Hello cyphar,

Thanks for your quick answer. I am not against the fact that you ask advice from CloudFoundry developers, if you have some direct access to them.

If I leet runC create an unprivileged network namespace, how can i see it from the host ?
With an "ip netns ls" command from the host, i don't see it (probably because it run also into this own pid namespace). 
 

Regarding the cgroup topic, what should be done inside config.json to have cgroup in rootless container mode ? If i check inside my container with a cat /proc/self/cgroup i have the same "mount point" as my host (if it run runc in root, if have a dedicated cgroup)

In rootless mode
```
$runc run foo

/ # cat /proc/self/cgroup 
11:devices:/user.slice
10:perf_event:/
9:net_cls,net_prio:/
8:freezer:/
7:memory:/user.slice
6:cpu,cpuacct:/user.slice
5:blkio:/user.slice
4:hugetlb:/
3:pids:/user.slice/user-1000.slice
2:cpuset:/
1:name=systemd:/user.slice/user-1000.slice/session-c4.scope

```

In root mode  (with the same config.json)
```
# run runc bar

# cat /proc/self/cgroup 
11:devices:/user.slice/bar
10:perf_event:/bar
9:net_cls,net_prio:/bar
8:freezer:/bar
7:memory:/user.slice/bar
6:cpu,cpuacct:/user.slice/bar
5:blkio:/user.slice/bar
4:hugetlb:/bar
3:pids:/user.slice/user-1000.slice/bar
2:cpuset:/bar
1:name=systemd:/user.slice/user-1000.slice/session-c4.scope/bar
```

**Comment by tangicolin** [comment] 2017-04-07 09:55
EDIT : I was stupidly use runc pid to nsenter, using sh pid of the container for nsenter pid work better and i'm able to see my network namespace (i will try to add some interface on it). I keep you inform of my progress and will post result here.

**Comment by tangicolin** [comment] 2017-04-07 10:12
Sorry for the spam, i post here the result of my investigation. 
At the moment i don't understand how i can add a virtual ethernet device to my unprivileged network namespace. 
Normally i will do that from Host global namespace by doing the following command : 
```
ip link set veth1 netns <networknamespace>
```
 But here i don't see this namespace from my host global namespace. I don't understand how nsenter can help me, i can create a virtual ethernet device inside my container network namespace (with nsenter) but how can i bridge it to a ethernet device in my global network namespace ?

**Comment by williammartin** [comment] 2017-04-07 10:48
Hey @tangicolin I'm from the CF Garden team. @cyphar has nailed exactly what we do. We let runc create an unprivileged network namespace and then we have a separate networking component with a `setuid` bit that sets up the veth pair. It would be nice to scope that down to the necessary capabilities but we haven't done that yet.

**Comment by tangicolin** [comment] 2017-04-07 13:06
Hi @cyphar  and @williammartin thank you for your help. 
Regarding CF tools, i have look at the right place it is done by kawasaki tools (https://github.com/cloudfoundry/guardian/blob/d426738a9001b2ad74502f0204fa9a50d91c3c9e/kawasaki/factory/factory_linux.go#L23)

I'm not a golang expert but if i understand well your code, you create a linux vpeer bridge on the host. 
So it is what i do by performing the command : 
`host#ip link add v-eth1 type veth peer name v-peer1`
But i'm currently facing with the issue to "give" v-peer to the container network namespace. I don't rely understand how and when it is done by your software. 
I want to do command : `ip link set v-peer1 netns <container network namespace>` but i don't know it for the host, runC doesn't create link in /var/run/netns, so i don't known how to access it. 
On your code the stuff probably happen with line `netns.Opener(os.open)` but i don't fully understand what happen behind and how i can do the same thing from shell. 

@cyphar : regarding cgroups topic (sorry for mux the thread, do you think i should open a dedicat issue for this to split cgroup and network topic), does it is normal if i run runc in rootless mode that i have not a cgroup create for my container (does some special stuff should be put in config.json to have it)?

**Comment by williammartin** [comment] 2017-04-07 13:25
Hi @tangicolin 

Yes you found our networking package. Now, to be clear this code will not run as an unprivileged user and this code is being deprecated in favour of a plugin that we can run with setuid. However, it seems you don't really care if you are rootless or not at this point, you are just figuring out how to create a `veth` pair and move one end into the namespace.

To see how we do this you can look at:

Veth Creation:

https://github.com/cloudfoundry/guardian/blob/master/kawasaki/configure/host.go#L59
https://github.com/cloudfoundry/guardian/blob/master/kawasaki/devices/veth_linux.go#L12

Moving Container side into network namespace:

https://github.com/cloudfoundry/guardian/blob/d426738a9001b2ad74502f0204fa9a50d91c3c9e/kawasaki/configure/host.go#L73-L76
https://github.com/cloudfoundry/guardian/blob/master/kawasaki/devices/link_linux.go#L73-L83

This is done using vishvananda's golang netlink library. the `ip` utility also uses netlink, but I'm not exactly sure on how to map the library to `ip` commands. 

https://github.com/vishvananda/netlink/blob/master/link_linux.go#L210-L214 seems to suggest it's the command you are trying.

**Comment by tangicolin** [comment] 2017-04-10 13:01
I have found my solution regarding how to add networking. To get the unprivilieged networking namespace, it simply exist in the link : /proc/<PID_OF_CONTAINER>/ns/net. ip nets search network namespace into /var/run/netns/, so with a basic symbolic link, after that i'm able to use the script  
https://gist.github.com/dpino/6c0dca1742093346461e11aa8f608a99 to create an network bridge mode. 

Does there is any reason for runC to not create a network namespace link inside /var/run/netns folder ? Does PR will be welcome for this feature ? 

So for networking it is solve.
I will start investigating cgroup support now. I just want to give cpu and memory limit to my whole container (from the host with privileged right).

**Comment by cyphar** [comment] 2017-04-10 13:25
@tangicolin 

> @cyphar : regarding cgroups topic (sorry for mux the thread, do you think i should open a dedicat issue for this to split cgroup and network topic), does it is normal if i run runc in rootless mode that i have not a cgroup create for my container (does some special stuff should be put in config.json to have it)?

By default if you use `runc spec --rootless` it will disable the creation of any cgroups (it will use the cgroups that the parent process of runC had when runC started). With rootless containers it's not possible to create your own cgroups (it's a kernel issue which I've tried to get resolved in the past) so if your config implies the creation of cgroups, runC will tell you that it's not possible to run such a container as an unprivileged user. In future I'm going to make it possible for runC to attempt to join cgroups on an opportunistic basis, but I've not had time to write that code yet. (I should probably add that to https://rootlesscontaine.rs/ now that I mention it.)

**Closed** 2017-06-09 08:16 UTC
