### ISSUE TITLE
s390x cgroupv2 runc error

### ISSUE THREAD

**Issue by cailca** [opencontainers/runc#2316] opened 2020-04-15 19:08 UTC
@AkihiroSuda @giuseppe @kolyshkin 

Using the latest upstream kernel and runc. s390x could not start runc with cgroupv2.

runc spec
runc run root

WARN[0001] signal: killed                               
ERRO[0001] container_linux.go:349: starting container process caused "process_linux.go:439: container init caused \"process_linux.go:405: setting cgroup config for procHooks process caused \\\"error while setting cgroup v2: [can't load program:\\\\n    github.com/cilium/ebpf.newProgramWithBTF\\\\n        /root/go/pkg/mod/github.com/cilium/ebpf@v0.0.0-20200319110858-a7172c01168f/prog.go:151\\\\n  - permission denied: 0: (69) r1 = *(u16 *)(r2 +0)\\\\nR2 !read_ok\\\\nprocessed 1 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0]\\\"\"" 
container_linux.go:349: starting container process caused "process_linux.go:439: container init caused \"process_linux.go:405: setting cgroup config for procHooks process caused \\\"error while setting cgroup v2: [can't load program:\\\\n    github.com/cilium/ebpf.newProgramWithBTF\\\\n        /root/go/pkg/mod/github.com/cilium/ebpf@v0.0.0-20200319110858-a7172c01168f/prog.go:151\\\\n  - permission denied: 0: (69) r1 = *(u16 *)(r2 +0)\\\\nR2 !read_ok\\\\nprocessed 1 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0]\\\"\""

**Comment by AkihiroSuda** [comment] 2020-04-15 19:16
Rootful or rootless?
Also make sure `CONFIG_CGROUP_BPF=y CONFIG_CGROUP_DEVICE=y`

**Comment by cailca** [comment] 2020-04-15 19:20
Just root. Having all the configs. The thing is that it passed for all other arches here except s390x.

# grep BPF linux/.config
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y

# grep CGROUP linux/.config
CONFIG_CGROUPS=y
CONFIG_BLK_CGROUP=y
CONFIG_CGROUP_WRITEBACK=y
CONFIG_CGROUP_SCHED=y
CONFIG_CGROUP_PIDS=y
CONFIG_CGROUP_RDMA=y
CONFIG_CGROUP_FREEZER=y
CONFIG_CGROUP_HUGETLB=y
CONFIG_CGROUP_DEVICE=y
CONFIG_CGROUP_CPUACCT=y
CONFIG_CGROUP_PERF=y
CONFIG_CGROUP_BPF=y
CONFIG_CGROUP_DEBUG=y
CONFIG_SOCK_CGROUP_DATA=y

**Comment by AkihiroSuda** [comment] 2020-04-15 19:22
cc @estesp

**Comment by estesp** [comment] 2020-04-15 22:09
@alicefr do you know who might be able to look into this? @cailca what distro is running on your s390x partition?

**Comment by cailca** [comment] 2020-04-15 22:25
> @alicefr do you know who might be able to look into this? @cailca what distro is running on your s390x partition?

RHEL 8.1+ but with the latest upstream kernel and runc.

**Comment by alicefr** [comment] 2020-04-16 05:56
Hi @estesp , I can try to reproduce it on my system. @cailca can you please describe a little bit more in detail which kernel have you used and how did you install it?

**Comment by giuseppe** [comment] 2020-04-16 07:44
I think the issue is in the eBPF code.

runc probably needs the equivalent of: https://github.com/containers/crun/commit/07bae05e613df2086966a3f1d763729a8677f6a9

**Comment by alicefr** [comment] 2020-04-16 07:51
ouch @giuseppe good catch!I'll have a try

**Comment by alicefr** [comment] 2020-04-16 09:42
I was able to reproduce the issues on a Fedora 31 with default kernel and upstream runc. I'll have a closer look

**Comment by alicefr** [comment] 2020-04-16 11:43
Strace output:
```
[...]
stat("/root/go/src/github.com/opencontainers/runc/test-runc", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
geteuid()                               = 0
openat(AT_FDCWD, "/proc/self/uid_map", O_RDONLY|O_CLOEXEC) = 3
epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1023, u64=4396460756744}}) = -1 EPERM (Operation not permitted)
epoll_ctl(4, EPOLL_CTL_DEL, 3, 0xc000138fc8) = -1 EPERM (Operation not permitted)
read(3, "         0          0 4294967295"..., 4096) = 33
read(3, "", 4063)                       = 0
close(3)                
[...]
```

**Comment by alicefr** [comment] 2020-04-16 12:36
@giuseppe I tried to apply the change you suggest:
```diff
git diff
diff --git a/libcontainer/cgroups/ebpf/devicefilter/devicefilter.go b/libcontainer/cgroups/ebpf/devicefilter/devicefilter.go
index 847ce8ef..18f7e4d1 100644
--- a/libcontainer/cgroups/ebpf/devicefilter/devicefilter.go
+++ b/libcontainer/cgroups/ebpf/devicefilter/devicefilter.go
@@ -49,7 +49,8 @@ func (p *program) init() {
        */
        // R2 <- type (lower 16 bit of u32 access_type at R1[0])
        p.insts = append(p.insts,
-               asm.LoadMem(asm.R2, asm.R1, 0, asm.Half))
+               asm.LoadMem(asm.R2, asm.R1, 0, asm.Word),
+               asm.And.Imm32(asm.R2, 16))
 
        // R3 <- access (upper 16 bit of u32 access_type at R1[0])
        p.insts = append(p.insts,

```
but I still get the same behavior.

**Comment by giuseppe** [comment] 2020-04-16 16:13
Are you able to run a different eBPF program on Fedora (e.g. `yum install -y bcc-tools && /usr/share/bcc/tools/execsnoop`)?

On x86_64 I had to disable secure boot for eBPF to work

**Comment by alicefr** [comment] 2020-04-17 06:14
@giuseppe yes, I'm able to execute it without any further configurations.

**Comment by alicefr** [comment] 2020-04-17 07:27
strace output
[strace-output.txt](https://github.com/opencontainers/runc/files/4491555/strace-output.txt)

**Comment by alicefr** [comment] 2020-04-17 07:30
I also tried to run `crun` and that works without any problems. So, it must be an issue with runc

**Comment by alicefr** [comment] 2020-04-17 12:14
it is an issue in the `https://github.com/cilium/ebpf `
I run a test:
```sh
go test -run TestProgramRun
--- FAIL: TestProgramRun (0.00s)
    prog_test.go:50:     0: LdXMemW dst: r2 src: r1 off: 4 imm: 0
             1: LdXMemW dst: r1 src: r1 off: 0 imm: 0
             2: MovReg dst: r3 src: r1
             3: AddImm dst: r3 imm: 14
             4: JGTReg dst: r3 off: -1 src: r2 <out>
             5: StMemB dst: r1 src: r0 off: 0 imm: 222
             6: StMemB dst: r1 src: r0 off: 1 imm: 173
             7: StMemB dst: r1 src: r0 off: 2 imm: 190
             8: StMemB dst: r1 src: r0 off: 3 imm: 239
        out:
             9: LdImmDW dst: r0 imm: 42
            11: Exit
        
    prog_test.go:59: can't load program: permission denied: 0: (61) r1 = *(u32 *)(r2 +4)
        R2 !read_ok
        processed 1 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
FAIL
exit status 1
FAIL    github.com/cilium/ebpf  0.001s
Collapse

```

**Comment by alicefr** [comment] 2020-04-17 12:23
Open an issue in the ebpf repository https://github.com/cilium/ebpf/issues/86

**Comment by alicefr** [comment] 2020-04-24 10:07
So, we have a fix for runc. This requires a fix in the clium/ebpf library (a PR will follow) and this [fix](https://github.com/opencontainers/runc/pull/2350). This PR #2350 fixes the same issues as @giuseppe already reported.

**Comment by alicefr** [comment] 2020-05-04 06:12
Ebpf PR to fix registers on s390x: https://github.com/cilium/ebpf/pull/91

**Comment by alicefr** [comment] 2020-05-08 06:52
cilium/ebpf#91 was merged. #2389 update the `github.com/cilium/ebpf` package

**Closed** 2020-05-08 14:06 UTC
