### ISSUE TITLE
Support runc on FreeBSD platform

### ISSUE THREAD

**Issue by clovertrail** [opencontainers/runc#1501] opened 2017-06-29 09:46 UTC
runc does not support FreeBSD yet. It is a required feature.

FreeBSD, as a Unix-like OS, is very famous in virtual appliance industry. It has its own container mechanism: jail, and it also has the quotas framework: resource control (rctl). But it does not have checkpoint/restore mechanism in user space. It deserves to take some efforts to support runc on FreeBSD.

A lot of FreeBSD users are eager to see container feature ready on FreeBSD platform.

**Comment by cyphar** [comment] 2017-06-29 10:11
> runc does not support FreeBSD yet. It is a required feature.

`runc` is a Linux-specific container runtime, so it's not a "required feature". Also this language is fairly aggressive and I don't understand why.

> A lot of FreeBSD users are eager to see container feature ready on FreeBSD platform.

I have a lot of respect for FreeBSD, and there is no reason that someone cannot create a FreeBSD OCI runtime. The whole point of the OCI is that you can create several different implementations of the same standard that are interoperable. Forcing one implementation to do everything is counter to that.

However, I will note that if the FreeBSD community really wants to see OCI container runtimes for FreeBSD (and I say this as someone who has always had respect for the BSD family) you need to get more involved in the specification drafting process. Currently FreeBSD is completely unrepresented in the OCI specification, meaning that it's not clear to users how one would use an OCI container on a FreeBSD environment. I have reached out to some FreeBSD folks in the past, and they showed some interest but I have yet to see the fruits of their labour unfortunately.

**Comment by clovertrail** [comment] 2017-06-30 03:16
I have done some explorations on that, and I have finished some initial tasks by implementing some of runc commands, for example, run, ps, delete, etc, based on FreeBSD jails. I'd like to contribute them if you think it makes sense.

**Comment by clovertrail** [comment] 2017-06-30 03:40
@cyphar As you said, FreeBSD community shows interest but does not do any concrete progress. In 2015, there is an dockerd implementation on FreeBSD [,](https://github.com/kvasdopil/docker/tree/freebsd-compat), but after that, there is no further involvement from FreeBSD community. If nobody try on that, then there is no progress. I prefer to implement some features to push this going forward.

**Comment by AkihiroSuda** [comment] 2017-06-30 05:59
@clovertrail 

The first thing would be to define OCI spec for FreeBSD? https://github.com/opencontainers/runtime-spec/

**Comment by cyphar** [comment] 2017-06-30 06:05
:+1: on what @AkihiroSuda said. The most meaningful contribution to this effort and to the OCI would be to propose support for FreeBSD **in the spec** (preferably based on an existing implementation). If you want to base your implementation on `runc` that's fine, but we don't have plans to support non-Linux platforms -- purely because adding support for more platforms in `runc` would mean that fewer people would work on separate implementations of the OCI specs (everyone would just use us) which would lead to the OpenSSL problem.

**Comment by clovertrail** [comment] 2017-06-30 06:33
@AkihiroSuda OCI spec for FreeBSD is another task I'm working on.

**Comment by clovertrail** [comment] 2017-06-30 06:41
@cyphar As you said, runc is purely for Linux platform and there is no plan to support non-Linux platforms. I also observed solaris was removed. Do you mean you do not plan to accept any contribution from other platforms?

**Comment by cyphar** [comment] 2017-06-30 06:44
> Do you mean you do not plan to accept any contribution from other platforms?

Not at the moment. Again, the reason for this is **not** that I don't want a FreeBSD runtime. The reason is that if `runc` becomes the monolith of OCI containing implementations of everything, then the whole point of standardising runtimes is a bit pointless at that point. You also run into the OpenSSL issue, that nobody will contest when the "big player" decides to change the spec for the worse.

**Comment by clovertrail** [comment] 2017-06-30 06:54
@cyphar Understand. Making runc clean is good for a long term development. I'll find other ways to do OCI exploration for FreeBSD. Thanks.

**Comment by dqminh** [comment] 2017-07-05 12:02
@clovertrail Thanks for starting the discussion. As we have no plan for this right now, i'm going to close this  issue. If you would like to fork `runc` and make it works with FreeBSD that would be awesome !

**Closed by dqminh** 2017-07-05 12:02 UTC

**Comment by AkihiroSuda** [comment] 2018-06-17 22:54
I found @clovertrail 's forked runc for FreeBSD here: https://github.com/clovertrail/runc/tree/1501-SupportOnFreeBSD 👍 

If you are still interested in, could you consider opening `runtime-spec` issue/PR and rename you repo to non-runc name?

**Comment by kris-nova** [comment] 2021-03-17 01:07
hi 👋🏻 

would love to get involved with this, and donate some kris nóva hours to the cause. what would be the best way for me to get involved? do we have any upcoming meetings or mailing lists tracking the work?

**Comment by dims** [comment] 2021-03-17 01:16
@kris-nova others ... for the record - https://github.com/samuelkarp/runj

**Comment by samuelkarp** [comment] 2021-03-23 22:12
I don't have any scheduled meetings or active mailing list discussions, but I'm working on an OCI runtime for FreeBSD jails in https://github.com/samuelkarp/runj.  Happy to have discussions there; my current plan is to get the runtime built and drive any potential changes to the OCI runtime spec upstream in the spec repo.
