### ISSUE TITLE
How to understand 'initWaiter' ?

### ISSUE THREAD

**Issue by granty1** [opencontainers/runc#3333] opened 2022-01-06 12:19 UTC
Hello, I recently  started trying to read runc code, encounter a little doubt:
1. https://github.com/opencontainers/runc/blob/c83abc503de7e8b3017276e92e7510064eee02a8/libcontainer/process_linux.go#L802 From the comments, it should be waiting for "runc init" to complete.
https://github.com/opencontainers/runc/blob/c83abc503de7e8b3017276e92e7510064eee02a8/libcontainer/nsenter/nsexec.c#L871
but in fact , this signal is sent at the beginning of nsenter. What does "initial setup" mean here?
2. Why do I need to wait? I read your git commit record, "start: don't kill runc too early". How can I understand this sentence.

I'm looking forward to your reply. I'd like to know ：）

**Comment by kolyshkin** [comment] 2022-01-25 07:03
@granty1 sometimes it helps to look into git history. For example, trying `git blame` for the code in question, we can find out that it was added by commit 4ecff8d9d886e31d8a1d4fbb7836782327b380db.

Looking into that commit, you'll see the commit message that (hopefully) describes what was done and why.

Let me know if you have any more questions after reading that commit.

**Comment by kolyshkin** [comment] 2022-01-25 07:05
> From the comments, it should be waiting for "runc init" to complete.

The comment says "for making sure runc init has finished the initial setup", not the "runc init to complete".

The commit message from the commit linked above provides more info about why.

**Comment by kolyshkin** [comment] 2022-01-25 07:06
Closing as this is not a bug, but thank you for your interest, @granty1

**Closed by kolyshkin** 2022-01-25 07:06 UTC
Labels: kind/question

**Comment by granty1** [comment] 2022-01-27 05:20
I saw it after watching it carefully,  thanks for your answer 👍🏽
