### ISSUE TITLE
Attach to a running container?

### ISSUE THREAD

**Issue by jwendell** [opencontainers/runc#1416] opened 2017-04-22 19:40 UTC
Is there a way to attach to a running container (like one started by runc create/start)?

**Comment by cyphar** [comment] 2017-04-23 08:32
Not by default (at least in the way that you mean). `runc create` and `runc start` are **not analogous** to `docker create` and `docker start`. They fulfill entirely different purposes and any apparent similarities are unfortunate and coincidental.

If you want to be able to access the stdio of the container, you can use `--console-socket` (with `runc run -d` or `runc create`+`runc start`), create your own stdio (also with `runc run -d` or `runc create`+`runc start`), or wrap around `runc run`.

`runc create`/`runc start` are used to allow external processes to mutate the state of the container's environment before your main process  starts. In addition, it causes runc to be in a detached state (by nature) and thus runc doesn't have any code running once the container process starts (runc is daemonless by design). Thus, if you want the ability to attach to the IO of the container you'd need to implement that yourself (or use a manager of runc that does it for you).

For more information, read the [runtime-spec](https://github.com/opencontainers/runtime-spec) (specifically the lifecycle of containers).

**Comment by sak0** [comment] 2017-04-23 10:58
there is no implement like `docker attach`,  and you can use `runc exec $container_id $cmd` to run process in same namespace with the container started by runc

**Comment by crosbymichael** [comment] 2017-04-25 18:13
This is out of scope for runc because we don't own the IO for the process.  That is handled at the higher layers and needs to be implemented there.

**Closed by crosbymichael** 2017-04-25 18:13 UTC
