### ISSUE TITLE
1.0 rc (04f275d) will automately quit

### ISSUE THREAD

**Issue by slayercat** [opencontainers/runc#990] opened 2016-08-17 18:54 UTC
version: 04f275d

when use `runc create ` command,  the runc program will sometimes quit, left container not destoryed.

normally this is not a problem. but i'm in systemd env. so it will

 1) cause systemd try restart container. which will fail, for theres same container running.
 2) systemd cannot stop the container.

i have two container with the same issue. one config below

trying version v0.1.1 now.

```
{
  "ociVersion": "1.0.0-rc1",
  "platform": {
    "os": "linux",
    "arch": "amd64"
  },
  "process": {
    "terminal": false,
    "user": {
      "uid": 0,
      "gid": 0
    },
    "args": [
      "bash", "/start.sh"
    ],
    "env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "TERM=xterm",
      "HOME=/dev/shm",
      "SCYLLA_MEM_SIZE=1G"
    ],
    "cwd": "/",
    "capabilities": [
      "CAP_AUDIT_WRITE",
      "CAP_KILL",
      "CAP_NET_BIND_SERVICE",
      "CAP_NET_ADMIN",
      "CAP_NET_RAW",
      "CAP_SETUID",
      "CAP_SETGID",
      "CAP_CHOWN",
      "CAP_FOWNER",
      "CAP_DAC_OVERRIDE",
      "CAP_SYS_RESOURCE"
    ],
    "rlimits": [
      {
        "type": "RLIMIT_NOFILE",
        "hard": 10240,
        "soft": 10240
      }
    ],
    "noNewPrivileges": false
  },
  "root": {
    "path": "rootfs",
    "readonly": false
  },
  "hostname": "scylladb",
  "mounts": [
    {
      "destination": "/proc",
      "type": "proc",
      "source": "proc"
    },
    {
      "destination": "/dev",
      "type": "tmpfs",
      "source": "tmpfs",
      "options": [
        "nosuid",
        "strictatime",
        "mode=755",
        "size=65536k"
      ]
    },
    {
      "destination": "/dev/pts",
      "type": "devpts",
      "source": "devpts",
      "options": [
        "nosuid",
        "noexec",
        "newinstance",
        "ptmxmode=0666",
        "mode=0620",
        "gid=5"
      ]
    },
    {
      "destination": "/dev/shm",
      "type": "tmpfs",
      "source": "shm",
      "options": [
        "nosuid",
        "noexec",
        "nodev",
        "mode=1777",
        "size=65536k"
      ]
    },
    {
      "destination": "/dev/mqueue",
      "type": "mqueue",
      "source": "mqueue",
      "options": [
        "nosuid",
        "noexec",
        "nodev"
      ]
    },
    {
      "destination": "/sys",
      "type": "sysfs",
      "source": "sysfs",
      "options": [
        "nosuid",
        "noexec",
        "nodev",
        "mode=0400"
      ]
    },
    {
      "destination": "/sys/fs/cgroup",
      "type": "cgroup",
      "source": "cgroup",
      "options": [
        "nosuid",
        "noexec",
        "nodev",
        "relatime",
        "ro"
      ]
    },
    {
      "destination": "/sys/bus/pci/",
      "type":  "tmpfs",
      "source":    "shm",
      "options": [ "size=1k" ]
    },
    {
      "destination": "/sys/bus/pci/devices",
      "type":  "tmpfs",
      "source":    "shm",
      "options": [ "size=1k" ]
    },
    {
      "destination": "/var/lib/scylla/",
      "type": "none",
      "source": "/opt/xxxx/userdata/scylla",
      "options": [
        "bind"
      ]
    }
  ],
  "linux": {
    "sysctl":{
        "net.ipv6.conf.all.disable_ipv6":"1"
    },
    "resources": {
      "memory": {
        "limit": 4294967296,
        "reservation": 2147483648
      },
      "devices": [
      ]
    },
    "namespaces": [
      {
        "type": "pid"
      },
      {
        "type": "network",
        "path": "/run/netns/scylladb"
      },
      {
        "type": "ipc"
      },
      {
        "type": "uts"
      },
      {
        "type": "mount"
      }
    ],
    "maskedPaths": [
      "/proc/sys/bus/pci",
      "/proc/kcore",
      "/proc/latency_stats",
      "/proc/timer_stats",
      "/proc/sched_debug"
    ],
    "readonlyPaths": [
      "/proc/asound",
      "/proc/bus",
      "/proc/fs",
      "/proc/irq",
      "/proc/sys",
      "/proc/sysrq-trigger"
    ]
  },
  "solaris": {
    "cappedCPU": {

    },
    "cappedMemory": {

    }
  }
}

```

systemd config:
```
[Unit]
Description=xxxxxx
After=network.target 
PartOf=xxxxx

[Service]
Type=simple
ExecStartPre=set_network.sh
ExecStart=runc start scylladb
WorkingDirectory=xxxxxx
KillMode=process
Restart=always
RestartSec=1s
StartLimitBurst= 0
Slice=xxx.slice

[Install]
WantedBy=multi-user.target

```

**Comment by slayercat** [comment] 2016-08-17 19:12
a simple test shows in ver 0.1.1 (baf6536d6259209c3edfa2b22237af82942d3dfa),  systemd stop will not stop container, just kill runc.

```
[root@194-233 ~]# ps auxf|grep runc
root      35026  0.0  0.0 112652  2240 pts/0    S+   03:11   0:00  |       \_ grep --color=auto runc
[root@194-233 ~]# /opt/xxx/xxx/runc list
ID          PID         STATUS      BUNDLE                          CREATED
xxxxx      3331        running     /opt/xxxxxx     2016-08-17T18:53:32.720053196Z
xxxxxb    3321        running     /opt/xxxxxxxxxxx  2016-08-17T18:53:32.576006025Z

```

**Comment by slayercat** [comment] 2016-08-17 19:42
version 6df383c2f881fbdeb85060fd27d8bf61afedacd9 (master)

when systemd stop service, will left container  lived either

**Comment by cyphar** [comment] 2016-08-17 22:35
This is by design. We've split `create` into `create` and `start` -- where `create` doesn't start the users' process, it just creates the container namespace and waits for a signal to start the container. If you want to have the old semantics use `runc run`. The PR for this is #506.

Closing since it's by design. Feel free to re-open this issue if you find some problems with the new design.

**Closed by cyphar** 2016-08-17 22:35 UTC

**Comment by slayercat** [comment] 2016-08-18 01:52
question: how to make this design work with systemd?
@cyphar

**Comment by slayercat** [comment] 2016-08-18 01:55
the problem came from runc just quit so systemd cannot check it's state.

is this by design? @cyphar

**Comment by cyphar** [comment] 2016-08-18 09:37
There are two options: Just use `runc run` instead of `runc create` -- the semantics are the same as the old way that things used to work (in other words, if you replace all `runc create`s with `runc run`s in your scripts that used to work with older runC versions they should work with the new version).

The other option is to create a more complicated unit file that uses both `runc create` and `runc start`. I wouldn't really recommend it though, since you won't gain much (the split is for orchestrators, not for regular end-users).
