### ISSUE TITLE
[system tests] exec failed: open /dev/tty: no such device or address

### ISSUE THREAD

**Issue by chuanchang** [opencontainers/runc#3096] opened 2021-07-17 09:04 UTC
The system tests don't work well in CI environment, and there are many tests are failed due to "exec failed: open /dev/tty: no such device or address", this issue can be hit in {rootless, rootful} + {cgroupv1, cgroupv2} mode.

```
16:37:14  not ok 29 global --debug
16:37:14  # (in test file tests/integration/debug.bats, line 22)
16:37:14  #   `[ "$status" -eq 0 ]' failed
16:37:14  # runc spec --rootless (status=0):
16:37:14  # 
16:37:14  # runc --debug run test_hello (status=1):
16:37:14  # time="2021-07-17T04:37:12-04:00" level=error msg="open /dev/tty: no such device or address" func=main.fatal file="/builddir/build/BUILD/runc-1.0.0-rc95/GOPATH/src/github.com/opencontainers/runc/GOPATH/src/github.com/opencontainers/runc/utils.go:57"
16:37:14  # time="2021-07-17T04:37:12-04:00" level=debug msg="open /dev/tty: no such device or address" func=main.fatal file="/builddir/build/BUILD/runc-1.0.0-rc95/GOPATH/src/github.com/opencontainers/runc/GOPATH/src/github.com/opencontainers/runc/utils.go:59"
16:37:14  not ok 30 global --debug to --log
16:37:14  # (in test file tests/integration/debug.bats, line 32)
16:37:14  #   `[ "$status" -eq 0 ]' failed
16:37:14  # runc spec --rootless (status=0):
16:37:14  # 
16:37:14  # runc --log log.out --debug run test_hello (status=1):
16:37:14  # open /dev/tty: no such device or address
16:37:15  not ok 31 global --debug to --log --log-format 'text'
16:37:15  # (in test file tests/integration/debug.bats, line 47)
16:37:15  #   `[ "$status" -eq 0 ]' failed
16:37:15  # runc spec --rootless (status=0):
16:37:15  # 
16:37:15  # runc --log log.out --log-format text --debug run test_hello (status=1):
16:37:15  # open /dev/tty: no such device or address
16:37:15  not ok 32 global --debug to --log --log-format 'json'
16:37:15  # (in test file tests/integration/debug.bats, line 62)
16:37:15  #   `[ "$status" -eq 0 ]' failed
16:37:15  # runc spec --rootless (status=0):
16:37:15  # 
16:37:15  # runc --log log.out --log-format json --debug run test_hello (status=1):
16:37:15  # open /dev/tty: no such device or address


16:37:23  not ok 38 runc run [redundant default /dev/tty]
16:37:23  # (in test file tests/integration/dev.bats, line 18)
16:37:23  #   `[ "$status" -eq 0 ]' failed
16:37:23  # runc spec --rootless (status=0):
16:37:23  # 
16:37:23  # runc run test_dev (status=1):
16:37:23  # time="2021-07-17T04:37:16-04:00" level=error msg="open /dev/tty: no such device or address"
16:37:23  not ok 39 runc run [redundant default /dev/ptmx]
16:37:23  # (in test file tests/integration/dev.bats, line 32)
16:37:23  #   `[ "$status" -eq 0 ]' failed
16:37:23  # runc spec --rootless (status=0):
16:37:23  # 
16:37:23  # runc run test_dev (status=1):
16:37:23  # time="2021-07-17T04:37:16-04:00" level=error msg="open /dev/tty: no such device or address"


16:37:31  not ok 67 runc run [bind mount]
16:37:31  # (in test file tests/integration/mounts.bats, line 22)
16:37:31  #   `[ "$status" -eq 0 ]' failed
16:37:31  # runc spec --rootless (status=0):
16:37:31  # 
16:37:31  # runc run test_busybox (status=1):
16:37:31  # time="2021-07-17T04:37:29-04:00" level=error msg="open /dev/tty: no such device or address"
16:37:31  not ok 68 runc run [ro tmpfs mount]
16:37:31  # (in test file tests/integration/mounts.bats, line 36)
16:37:31  #   `[ "$status" -eq 0 ]' failed
16:37:31  # runc spec --rootless (status=0):
16:37:31  # 
16:37:31  # runc run test_busybox (status=1):
16:37:31  # time="2021-07-17T04:37:29-04:00" level=error msg="open /dev/tty: no such device or address"
16:37:31  not ok 69 runc run [tmpfs mount with absolute symlink]
16:37:31  # (in test file tests/integration/mounts.bats, line 53)
16:37:31  #   `[ "$status" -eq 0 ]' failed
16:37:31  # runc spec --rootless (status=0):
16:37:31  # 
16:37:31  # runc run test_busybox (status=1):
16:37:31  # time="2021-07-17T04:37:30-04:00" level=error msg="open /dev/tty: no such device or address"


16:37:36  not ok 78 runc run [seccomp -ENOSYS handling]
16:37:36  # (in test file tests/integration/seccomp.bats, line 22)
16:37:36  #   `[ "$status" -eq 0 ]' failed
16:37:36  # runc spec --rootless (status=0):
16:37:36  # 
16:37:36  # runc run test_busybox (status=1):
16:37:36  # time="2021-07-17T04:37:34-04:00" level=error msg="open /dev/tty: no such device or address"
16:37:36  not ok 79 runc run [seccomp defaultErrnoRet=ENXIO]
16:37:36  # (in test file tests/integration/seccomp.bats, line 34)
16:37:36  #   `[ "$status" -eq 0 ]' failed
16:37:36  # runc spec --rootless (status=0):
16:37:36  # 
16:37:36  # runc run test_busybox (status=1):
16:37:36  # time="2021-07-17T04:37:35-04:00" level=error msg="open /dev/tty: no such device or address"
16:37:36  not ok 80 spec generation cwd
16:37:36  # (in test file tests/integration/spec.bats, line 15)
16:37:36  #   `[ "$status" -eq 0 ]' failed
16:37:36  # runc spec --rootless (status=0):
16:37:36  # 
16:37:36  # runc run test_hello (status=1):
16:37:36  # time="2021-07-17T04:37:35-04:00" level=error msg="open /dev/tty: no such device or address"
[Pipeline] sh
16:37:38  not ok 81 spec generation --bundle
16:37:38  # (in test file tests/integration/spec.bats, line 20)
16:37:38  #   `[ "$status" -eq 0 ]' failed
16:37:38  # runc spec --rootless (status=0):
16:37:38  # 
16:37:38  # runc run --bundle /tmp/bats-run-31104/runc.97cVzN/bundle test_hello (status=1):
16:37:38  # time="2021-07-17T04:37:35-04:00" level=error msg="open /dev/tty: no such device or address"


16:37:48  not ok 88 runc run
16:37:48  # (in test file tests/integration/start_hello.bats, line 16)
16:37:48  #   `[ "$status" -eq 0 ]' failed
16:37:48  # runc spec --rootless (status=0):
16:37:48  # 
16:37:48  # runc run test_hello (status=1):
16:37:48  # time="2021-07-17T04:37:41-04:00" level=error msg="open /dev/tty: no such device or address"


16:37:48  not ok 90 runc run with rootfs set to .
16:37:48  # (in test file tests/integration/start_hello.bats, line 47)
16:37:48  #   `[ "$status" -eq 0 ]' failed
16:37:48  # runc spec --rootless (status=0):
16:37:48  # 
16:37:48  # runc run test_hello (status=1):
16:37:48  # time="2021-07-17T04:37:42-04:00" level=error msg="open /dev/tty: no such device or address"
16:37:48  not ok 91 runc run --pid-file
16:37:48  # (in test file tests/integration/start_hello.bats, line 54)
16:37:48  #   `[ "$status" -eq 0 ]' failed
16:37:48  # runc spec --rootless (status=0):
16:37:48  # 
16:37:48  # runc run --pid-file pid.txt test_hello (status=1):
16:37:48  # time="2021-07-17T04:37:42-04:00" level=error msg="open /dev/tty: no such device or address"
16:37:48  not ok 92 runc run [rootless with host pidns]
16:37:48  # (in test file tests/integration/start_hello.bats, line 77)
16:37:48  #   `[ "$status" -eq 0 ]' failed
16:37:48  # runc spec --rootless (status=0):
16:37:48  # 
16:37:48  # runc run test_hello (status=1):
16:37:48  # time="2021-07-17T04:37:42-04:00" level=warning msg="cannot toggle freezer: cgroups not configured for container"
16:37:48  # time="2021-07-17T04:37:42-04:00" level=warning msg="cannot toggle freezer: cgroups not configured for container"
16:37:48  # time="2021-07-17T04:37:42-04:00" level=warning msg="lstat : no such file or directory"
16:37:48  # time="2021-07-17T04:37:42-04:00" level=error msg="open /dev/tty: no such device or address"


16:37:48  not ok 95 runc run [stdin not a tty]
16:37:48  # (in test file tests/integration/tty.bats, line 18)
16:37:48  #   `[ "$status" -eq 0 ]' failed
16:37:48  # runc spec --rootless (status=0):
16:37:48  # 
16:37:48  # runc run test_busybox (status=1):
16:37:48  # time="2021-07-17T04:37:43-04:00" level=error msg="open /dev/tty: no such device or address"
16:37:48  not ok 96 runc run [tty ptsname]
16:37:48  # (in test file tests/integration/tty.bats, line 28)
16:37:48  #   `[ "$status" -eq 0 ]' failed
16:37:48  # runc spec --rootless (status=0):
16:37:48  # 
16:37:48  # runc run test_busybox (status=1):
16:37:48  # time="2021-07-17T04:37:44-04:00" level=error msg="open /dev/tty: no such device or address"


6:37:48  not ok 99 runc exec [stdin not a tty]
16:37:48  # (in test file tests/integration/tty.bats, line 80)
16:37:48  #   `[ "$status" -eq 0 ]' failed
16:37:48  # runc spec --rootless (status=0):
16:37:48  # 
16:37:48  # runc run -d --console-socket /tmp/bats-run-31104/runc.G3HpQW/tty/sock test_busybox (status=0):
16:37:48  # 
16:37:48  # runc state test_busybox (status=0):
16:37:48  # {
16:37:48  #   "ociVersion": "1.0.2-dev",
16:37:48  #   "id": "test_busybox",
16:37:48  #   "pid": 38158,
16:37:48  #   "status": "running",
16:37:48  #   "bundle": "/tmp/bats-run-31104/runc.G3HpQW/bundle",
16:37:48  #   "rootfs": "/tmp/bats-run-31104/runc.G3HpQW/bundle/rootfs",
16:37:48  #   "created": "2021-07-17T08:37:45.578372102Z",
16:37:48  #   "owner": ""
16:37:48  # }
16:37:48  # runc exec -t test_busybox sh -c stty size (status=1):
16:37:48  # time="2021-07-17T04:37:45-04:00" level=error msg="exec failed: open /dev/tty: no such device or address"
16:37:48  not ok 100 runc exec [tty ptsname]
16:37:48  # (in test file tests/integration/tty.bats, line 94)
16:37:48  #   `[ "$status" -eq 0 ]' failed
16:37:48  # runc spec --rootless (status=0):
16:37:48  # 
16:37:48  # runc run -d --console-socket /tmp/bats-run-31104/runc.9Drp3I/tty/sock test_busybox (status=0):
16:37:48  # 
16:37:48  # runc state test_busybox (status=0):
16:37:48  # {
16:37:48  #   "ociVersion": "1.0.2-dev",
16:37:48  #   "id": "test_busybox",
16:37:48  #   "pid": 38237,
16:37:48  #   "status": "running",
16:37:48  #   "bundle": "/tmp/bats-run-31104/runc.9Drp3I/bundle",
16:37:48  #   "rootfs": "/tmp/bats-run-31104/runc.9Drp3I/bundle/rootfs",
16:37:48  #   "created": "2021-07-17T08:37:46.071460874Z",
16:37:48  #   "owner": ""
16:37:48  # }
16:37:48  # runc exec -t test_busybox sh -c for file in /proc/self/fd/[012]; do readlink $file; done (status=1):
16:37:48  # time="2021-07-17T04:37:46-04:00" level=error msg="exec failed: open /dev/tty: no such device or address"
```

**Comment by cyphar** [comment] 2021-07-17 09:12
Can you clarify a bit more what you're trying to do? Our tests do work in at least our own CI environment. I expect the issue is that you are running in an environment that doesn't have a proper console (this is the default for GitHub Actions) or possibly through an SSH session. In either case, see https://github.com/opencontainers/runc/blob/master/.github/workflows/test.yml for how we worked around this problem (`script -e` for regular actions, and `ssh -tt` for Vagrant/SSH-based runs).

**Comment by chuanchang** [comment] 2021-07-17 10:52
> Can you clarify a bit more what you're trying to do? Our tests do work in at least our own CI environment. I expect the issue is that you are running in an environment that doesn't have a proper console (this is the default for GitHub Actions) or possibly 

I'm running upstream system tests on RHEL 8.4 in downstream Jenkins CI (PSI Openstack), it's not very easy to access Jenkins slave by SSH, because the slave is provisioned dynamically. 

> through an SSH session. In either case, see https://github.com/opencontainers/runc/blob/master/.github/workflows/test.yml for how we worked around this problem (`script -e` for regular actions, and `ssh -tt` for Vagrant/SSH-based runs).

I directly ran system tests by 'bats -t tests/integration' command in jenkins declarative pipeline, I'm not expert for 'script' command usage, could I use 'script -e bats -t tests/integration' to avoid tty issue? thanks a lot!

BTW, at present, I implemented a 'require tty' keyword to skip these failure tests on the local, I'm not sure if it's what we want.

**Comment by cyphar** [comment] 2021-07-17 11:17
> I'm not expert for 'script' command usage, could I use 'script -e bats -t tests/integration' to avoid tty issue? thanks a lot!

You can see how we use it in the link I gave you:

https://github.com/opencontainers/runc/blob/2749f1f18bafb062a28536bfca1d95cae65521c6/.github/workflows/test.yml#L69

(I mentioned SSH because for Vagrant we use `ssh -tt ...` -- but the effect is the same as using `script -e ...`.)

> BTW, at present, I implemented a 'require tty' keyword to skip these failure tests on the local, I'm not sure if it's what we want.

Not really, mainly because making sure runc's tty handling works is important enough (and should work on every kernel under the sun) that allowing the test to be skipped is not ideal.

**Comment by chuanchang** [comment] 2021-07-17 11:39
> You can see how we use it in the link I gave you:
> 
> https://github.com/opencontainers/runc/blob/2749f1f18bafb062a28536bfca1d95cae65521c6/.github/workflows/test.yml#L69
> 
> (I mentioned SSH because for Vagrant we use `ssh -tt ...` -- but the effect is the same as using `script -e ...`.)

Yes, I saw this line in test.yml, thank you for sharing this w/ me.

> Not really, mainly because making sure runc's tty handling works is important enough (and should work on every kernel under the sun) that allowing the test to be skipped is not ideal.

Agree, I just added **script -e -c 'bats -t tests/integration'** for rootless and **script -e -c 'sudo bats -t tests/integration'** for rootful in my pipeline script, basically, it works for me, but I still got other error as follows, it shouldn't be related to this issue I think:

cgroupv2: 
```
19:13:59  ok 1 runc create (no limits + no cgrouppath + no permission) succeeds
19:13:59  not ok 2 runc create (rootless + no limits + cgrouppath + no permission) fails with permission error
19:13:59  # (in test file tests/integration/cgroups.bats, line 25)
19:13:59  #   `[[ "$output" == *"unable to apply cgroup configuration"*"permission denied"* ]]' failed
19:13:59  # runc spec --rootless (status=0):
19:13:59  # 
19:13:59  # runc run -d --console-socket /tmp/bats-run-10986/runc.Bm6R83/tty/sock test_cgroups_permissions (status=1):
19:13:59  # time="2021-07-17T07:13:59-04:00" level=error msg="container_linux.go:380: starting container process caused: process_linux.go:385: applying cgroup configuration for process caused: mkdir /sys/fs/cgroup/runc-cgroups-integration-test: permission denied"

19:15:18  not ok 9 runc run (per-device io weight for bfq)
19:15:18  # (in test file tests/integration/cgroups.bats, line 187)
19:15:18  #   `[[ "$weights" == *"$major:$minor 444"* ]]' failed
19:15:18  # runc spec (status=0):
19:15:18  # 
19:15:18  # 1+0 records in
19:15:18  # 1+0 records out
19:15:18  # 4096 bytes (4.1 kB, 4.0 KiB) copied, 0.000155435 s, 26.4 MB/s
19:15:18  # runc run -d --console-socket /tmp/bats-run-19991/runc.7UWwwb/tty/sock test_dev_weight (status=0):
19:15:18  # 

19:18:08  not ok 118 update devices [minimal transition rules]
19:18:08  # (in test file tests/integration/update.bats, line 621)
19:18:08  #   `[ "$status" -eq 0 ]' failed
19:18:08  # runc spec (status=0):
19:18:08  # 
19:18:08  # runc run -d --console-socket /tmp/bats-run-19991/runc-tmp-recvtty.MoiQz2/console.sock test_update (status=1):
19:18:08  # time="2021-07-17T07:18:06-04:00" level=error msg="container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: unknown device access 97"
19:18:08  # [recvtty] fatal error: recvfd: incorrect number of bytes read (n=0 oobn=0)
```

cgroupv1:
```
19:14:07  ok 1 runc create (no limits + no cgrouppath + no permission) succeeds
19:14:07  not ok 2 runc create (rootless + no limits + cgrouppath + no permission) fails with permission error
19:14:07  # (in test file tests/integration/cgroups.bats, line 25)
19:14:07  #   `[[ "$output" == *"unable to apply cgroup configuration"*"permission denied"* ]]' failed
19:14:07  # runc spec --rootless (status=0):
19:14:07  # 
19:14:07  # runc run -d --console-socket /tmp/bats-run-11195/runc.KBJnDb/tty/sock test_cgroups_permissions (status=1):
19:14:07  # time="2021-07-17T07:14:06-04:00" level=warning msg="unable to get oom kill count" error="no directory specified for memory.oom_control"
19:14:07  # time="2021-07-17T07:14:06-04:00" level=error msg="container_linux.go:380: starting container process caused: process_linux.go:385: applying cgroup configuration for process caused: mkdir /sys/fs/cgroup/cpuset/runc-cgroups-integration-test: permission denied"

19:15:21  not ok 9 runc run (per-device io weight for bfq)
19:15:21  # (in test file tests/integration/cgroups.bats, line 175)
19:15:21  #   `[ "$status" -eq 0 ]' failed
19:15:21  # runc spec (status=0):
19:15:21  # 
19:15:21  # 1+0 records in
19:15:21  # 1+0 records out
19:15:21  # 4096 bytes (4.1 kB, 4.0 KiB) copied, 0.000157733 s, 26.0 MB/s
19:15:21  # runc run -d --console-socket /tmp/bats-run-20608/runc.P1EgpS/tty/sock test_dev_weight (status=1):
19:15:21  # time="2021-07-17T07:15:19-04:00" level=error msg="container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: open /sys/fs/cgroup/blkio/runc-cgroups-integration-test/test-cgroup-5442/blkio.weight: no such file or directory"
```

**Comment by cyphar** [comment] 2021-07-17 12:27
You need to use `tests/rootless.sh` to run the rootless integration tests, or otherwise re-implement the behaviour it has.

**Comment by chuanchang** [comment] 2021-07-17 12:37
> You need to use `tests/rootless.sh` to run the rootless integration tests, or otherwise re-implement the behaviour it has.

I created non-root users and rootless related configuration in the jenkins slave (as VM snapshot), so I haven't use `tests/rootless.sh`, I will re-read rootless.sh then see if I missed something, thanks!

**Comment by kolyshkin** [comment] 2021-08-19 03:06
Looks like the issue is no more; closing.

**Closed by kolyshkin** 2021-08-19 03:06 UTC
Labels: kind/question, area/ci
