### ISSUE TITLE
runc update --pids-limit 0  doesn't work

### ISSUE THREAD

**Issue by ningmingxiao** [opencontainers/runc#4566] opened 2024-12-20 07:00 UTC
### Description

runc update --pids-limit 0  doesn't work
https://github.com/opencontainers/runc/blob/ef5d2d4e354d8863e5d459bfbe37ca40f97037d5/libcontainer/cgroups/fs/pids.go#L22-L35
will ignore  PidsLimit=0

### Steps to reproduce the issue

runc update --pids-limit 0 

### Describe the results you received and expected

runc update --pids-limit 0  works sucessful

### What version of runc are you using?

any

### Host OS information

any

### Host kernel information

any

**Comment by lifubang** [comment] 2024-12-20 07:06
Similar issue: #4014

**Comment by cyphar** [comment] 2024-12-21 09:38
Yeah, this is a duplicate of #4014. The core issue is that the spec is written in a slightly unfortunate way (mea culpa, this was my fault originally) and so runc ended up with its current behaviour. #4014 and the linked spec issues from that issue can provide some more information.

**Closed by cyphar** 2024-12-21 09:38 UTC
