### ISSUE TITLE
How to add new network interface , such as ethX to runc instance?

### ISSUE THREAD

**Issue by cloudtrends** [opencontainers/runc#83] opened 2015-07-03 03:27 UTC
hi all,

I am using a centos base image to running runc instance .

After enter into the runc instance , I could found the default generated network interface file:
/etc/sysconfig/network-scripts/ifcfg-ens3

After config the above file , what confused me is that :  there is no support such as :
1) service network restart   or
2) /etc/init.d/network  
                             none above files exists in the runc instance .

Why I need the network interface is because that I want run a network service in runc , such as : 

python -m SimpleHTTPServer 8000

And above service can visited from outside of runc environment .

Can I archive this with runc ?

**Comment by kgrvamsi** [comment] 2015-07-06 13:35
i think the filesystem when the runc mounts will be a read only filesystem through rootfs and in returns dont create any pid files or saves any data in the necessary locations .I have this read-only issue when i was trying to check on some of the running resources packaged inside the container image

**Comment by wking** [comment] 2015-07-08 08:16
On Thu, Jul 02, 2015 at 08:27:23PM -0700, ChunFeng wrote:
> Why I need the network interface is because that I want run a
> network service in runc…

I'm not clear on the systemd connection that @kgrvamsi was suggesting,
but to me this sounds like a duplicate of #37.

**Comment by kgrvamsi** [comment] 2015-07-08 13:32
oh sorry if i'm wrong but the reffered issue gives me a light on this to try within the mounted container

     "root": {
        "path": "rootfs",
        "readonly": false 
       },

**Comment by LK4D4** [comment] 2015-07-08 14:17
@cloudtrends Now I think you can only create interface connected to host and then move it to your container namespace :/ Libcontainer has basic veth pair support though.

**Comment by crosbymichael** [comment] 2016-02-10 23:19
You can see my response here for how to setup networking for containers spawned by runc

https://github.com/opencontainers/runc/issues/201#issuecomment-182626457

Thanks!

**Closed by crosbymichael** 2016-02-10 23:19 UTC
