### ISSUE TITLE
Tag upcoming release as v1.0.1-rc.1 to fix go modules / SemVer comparison 

### ISSUE THREAD

**Issue by thaJeztah** [opencontainers/runc#2399] opened 2020-05-12 08:18 UTC
(Assuming we don't reach "GA" yet)

I was updating a dependency in a project using go modules, and noticed that the runc dependency was downgraded from `v1.0.0-rc10` to `v1.0.0-rc6` (a version specified in another dependency). Scratching my head why `v1.0.0-rc9` "stuck", but `v1.0.0-rc10` was "ignored" by go modules, I had a 🤦 moment, and recalled that the runc pre-release tags are missing a dot separator.

This worked until `-rc9`, but broke when `-rc10` was released;

Due to the missing separator in the release candidates:

```
v1.0.0-rc10
```

- `v` (prefix)
- `1` (major)
- `0` (minor)
- `0` (patch)
- `-` (it's a pre-release)
- `rc10` (pre-release suffix)

So for `v1.0.0-rc6`, the pre-release suffix (which is just anything you name it), is `rc6`, and for `v1.0.0-rc10`, the suffix is `rc10`.

These suffices are compared _alphabetically_, not _numerically_, only releases with the _same_ pre-release suffix are comparable.

So, when sorted alphabetically;

```
v1.0.0-rc1
v1.0.0-rc10
v1.0.0-rc2
v1.0.0-rc3
v1.0.0-rc4
v1.0.0-rc5
v1.0.0-rc6
v1.0.0-rc7
v1.0.0-rc8
v1.0.0-rc9
```

If a dot separator was used, the situation would be:

```
v1.0.0-rc.10
```

- `v` (prefix)
- `1` (major)
- `0` (minor)
- `0` (patch)
- `-` (it's a pre-release)
- `rc` (pre-release suffix)
- `10` (pre-release version for `rc` suffix)

In which case, the order (oldest -> newest) would be:

```
v1.0.0-rc.1
v1.0.0-rc.2
v1.0.0-rc.3
v1.0.0-rc.4
v1.0.0-rc.5
v1.0.0-rc.6
v1.0.0-rc.7
v1.0.0-rc.8
v1.0.0-rc.9
v1.0.0-rc.10
```

You can see the behavior here;

- without separator https://semvercompare.azurewebsites.net/?version=1.0.0-rc1&version=1.0.0-rc2&version=1.0.0-rc6&version=1.0.0-rc10&version=1.0.0-rc20
- with separator https://semvercompare.azurewebsites.net/?version=1.0.0-rc.1&version=1.0.0-rc.2&version=1.0.0-rc.6&version=1.0.0-rc.10&version=1.0.0-rc.20

I propose to skip v1.0.0, and tag the next -rc as `v1.0.1-rc.0` or `v1.0.1-rc.1`, in which case version comparison [works correct again](https://semvercompare.azurewebsites.net/?version=1.0.0-rc1&version=1.0.0-rc2&version=1.0.0-rc10&version=1.0.0-rc20&version=1.0.1-rc.1&version=1.0.1-rc.2&version=1.0.1-rc.10&version=1.0.1-rc.20&version=1.0.1-rc9.10)

```
v1.0.0-rc1
v1.0.0-rc10
v1.0.0-rc2
v1.0.0-rc20
v1.0.1-rc.1
v1.0.1-rc.2
v1.0.1-rc.10
v1.0.1-rc.20
```

**Comment by cyphar** [comment] 2020-05-12 09:00
While this is a correct implementation of SemVer, and it does match the behaviour described in the spec (though it is quite strange since I've never seen `1.x.y-rc.z` in any project, despite many projects using SemVer -- and `sort -V` does work properly):

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

I don't think doing a `1.0.1-rc.1` release is reasonable. Honestly, I'd be happier to go back and rename all of the releases (or make `rc10` `rc90`) than to skip over `1.0.0` over such a silly technicality...

**Comment by thaJeztah** [comment] 2020-05-12 09:26
It won't help with `-rc10`, but any project that would depend on `v1.0.1-rc.1` would not be _downgraded_ to `v1.0.0-rc9` (or lower). I considered adding new tags for each existing rc (`v1.0.0-rc1 -> v1.0.0-rc.1` and so on), but those new versions would be considered _lower_ than `rc1`; https://semvercompare.azurewebsites.net/?version=1.0.0-rc1&version=1.0.0-rc2&version=1.0.0-rc10&version=1.0.0-rc.1&version=1.0.0-rc.2&version=1.0.0-rc.10

> such a silly technicality

I'm not sure if it's a silly technicality at this point; projects getting an older version than expected looks like an actual problem to me.

**Comment by dims** [comment] 2020-05-12 10:14
I agree @thaJeztah it will trip up people if they are not paying close attention and hard to deal with using go modules as well.

**Comment by cyphar** [comment] 2020-05-12 11:22
My suggestion would be to just rename all of the releases -- since this only really affects go modules we just need to change the names of the tags (distributions don't care because they use `sort -V` order).

> I'm not sure if it's a silly technicality at this point; projects getting an older version than expected looks like an actual problem to me.

I wasn't trying to say it wasn't a problem, just that releasing a post-`1.0.0` release over this when compared to all of the other reasons why we've had to delay `1.0.0` does make this reason look like a "silly technicality" in comparison. I agree we should fix it.

**Comment by thaJeztah** [comment] 2020-05-12 11:37
> I will also note that there are many projects (including Moby/Docker) which use `-rcN`

Moby/Docker uses CalVer, so it would not be compatible anyway (well, until you have a `v17.12.x` release, and go modules thinks that's SemVer 😓))

I know containerd follows the SemVer notation (https://github.com/containerd/containerd/releases/tag/v1.3.0-rc.0), although there's still the discrepancy between SemVer and "go" SemVer (which requires the `v` prefix, which is explicitly [_not_ a SemVer version](https://semver.org/#is-v123-a-semantic-version), but that's another topic)

> My suggestion would be to just rename all of the releases 

You mean removing the existing tags, and replacing them? That sounds scary (and would break anyone that's already using on of these tags)

**Comment by cyphar** [comment] 2020-05-12 12:00
> That sounds scary (and would break anyone that's already using on of these tags).

Ah, right. Well then there's always the nuclear option -- tag `1.0.0-rc90` right now as being the same as `1.0.0-rc10` and then make `rc11` be `rc91`. That way we don't need to skip over `1.0.0` and we don't touch the old releases -- it's just that the `rc10` release becomes defunct as everyone uses the `rc90` release instead.

**Comment by thaJeztah** [comment] 2020-05-12 12:24
tbh, the diff between `v1.0.0-rc1` and `v1.0.0-rc10` is so big, that there's no relation whatsoever between them (it'd almost qualify as `v2.0.0`) 😂

> tag `1.0.0-rc90` right now as being the same as `1.0.0-rc10` and then make `rc11` be `rc91`. 

That should work; assuming we're confident that we don't reach `-rc100` 😬  as that would be lower than `-rc2` again

https://semvercompare.azurewebsites.net/?version=1.0.0-rc1&version=1.0.0-rc2&version=1.0.0-rc9&version=1.0.0-rc10&version=1.0.0-rc90&version=1.0.0-rc100

We're not alone in this, there's a reason Microsoft [never released a Windows 9](https://issues.jenkins-ci.org/secure/attachment/18777/PlatformDetailsTask.java) 😉

**Comment by cyphar** [comment] 2020-05-12 12:52
> That should work; assuming we're confident that we don't reach -rc100 grimacing as that would be lower than -rc2 again

That's when we roll out `rc990`. But I agree, let's hope it never comes to that.

**Comment by cyphar** [comment] 2020-05-12 13:02
@opencontainers/runc-maintainers Are there any objections to the above plan? I've already got an `-rc90` tag ready and waiting.

**Comment by dims** [comment] 2020-05-12 13:15
rc990 LOL!!! good one

**Comment by AkihiroSuda** [comment] 2020-05-12 13:16
:confused:

Can we just switch away from "rc" to another string. e.g. `v1.0.0-milestone.11` or `v1.0.0-rtm.11`

**Comment by AkihiroSuda** [comment] 2020-05-12 13:17
Or just give up the v1.0.0 dream and release `runc v11`.
This might be the best for reflecting the reality.

**Comment by AkihiroSuda** [comment] 2020-05-12 13:21
Or if we can release the `v1.0.0` in a month, I think we can just close this issue and call it a day.

**Comment by thaJeztah** [comment] 2020-05-12 13:30
> Can we just switch away from "rc" to another string. e.g. v1.0.0-milestone.11 or v1.0.0-rtm.11

`milestone` would be `<` `rc` (alphabetically). I was thinking along those lines as well, but would be equally confusing I think. That's why my first suggestion was to skip `v1.0.0` and use `v1.0.1-rc.X`.

**Comment by cyphar** [comment] 2020-05-13 01:08
> Or if we can release the v1.0.0 in a month, I think we can just close this issue and call it a day.

The issue is our existing release (`rc10`) is already causing this issue. At the very least we should have an `rc90` alias purely to stop people from downgrading their `runc` go modules.

**Comment by kolyshkin** [comment] 2020-05-13 01:42
`rtm` looks good. I.e.
```
v1.0.0-rc9 -> v1.0.0-rtm.9
v1.0.0-rc10 -> v1.0.0-rtm.10
...
```

`rc90` is OKish, too, but I like rtm more since we don't have to jump the number.

**Comment by AkihiroSuda** [comment] 2020-05-13 01:44
But it is not really "RTM" ¯\_(ツ)_/¯

**Comment by cyphar** [comment] 2020-05-13 01:50
I mean, let's just admit it and call it `1.0.0-runc.11` ;)

**Comment by kolyshkin** [comment] 2020-05-13 02:23
We can call it `1.0.0-sigma.11` without admitting anything :)

**Comment by thaJeztah** [comment] 2020-05-13 05:47
`v1.0.0-real-rc.11`, `v1.0.0-really-almost-there.1` or `v1.0.0-remember-to-add-a-.11` should all work 😂🤣

**Comment by cyphar** [comment] 2020-05-13 07:25
My vote is `v1.0.0-really-sorry-but-still-an-rc.11`. In all seriousness, I'll bring this up at the OCI call tomorrow.

**Comment by thaJeztah** [comment] 2020-05-13 09:13
Thanks @cyphar! (Just trying to keep a bit of "fun" in the situation)

**Comment by AkihiroSuda** [comment] 2020-05-28 01:13
What's the conclusion?

**Comment by mrunalp** [comment] 2020-05-28 04:36
I propose that we cut one more rc after #2229 , let other projects soak it, fix bugs if any and then call it 1.0.0 after a couple of weeks.

**Comment by cyphar** [comment] 2020-05-28 07:12
Right, but the issue is we need to switch to proper SemVer /somehow/. My vote is still for `rc90` because it doesn't require anyone to change how they're dealing with the rc releases (it just looks like we've done 80 of them in one go).

**Comment by mrunalp** [comment] 2020-05-28 14:02
Agree that `rc90` is least disruptive for the next release.

**Comment by cyphar** [comment] 2020-06-02 03:02
I've pushed v1.0.0-rc90 as a tag for v1.0.0-rc10 (a reminder that the the issue is that rc10 already has triggered this problem). So v1.0.0-rc91 will be v1.0.0-rc11.

**Closed by cyphar** 2020-06-02 03:02 UTC

**Comment by AkihiroSuda** [comment] 2020-06-02 03:07
@cyphar could you add release note (https://github.com/opencontainers/runc/issues/2399#issuecomment-627328348) ?

**Comment by cyphar** [comment] 2020-06-02 03:07
Yeah, just did it. :D

**Comment by cyphar** [comment] 2020-06-02 03:08
Yup, I was editing them just as you posted your comment. :wink: https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc90

**Comment by thaJeztah** [comment] 2020-06-02 06:56
It's a SameVer release
