### ISSUE TITLE
flag provided but not defined: -trimpath

### ISSUE THREAD

**Issue by cnjeffliu** [opencontainers/runc#3347] opened 2022-01-24 08:50 UTC
I build the dockerd from source code. When step into  build runc,  I get error :

Step 34/49 : RUN apt-get install -y libseccomp-dev
 ---> Using cache
 ---> 704f06e3da4d
Step 35/49 : RUN git clone https://github.com/opencontainers/runc.git /go/src/github.com/opencontainers/runc
 ---> Using cache
 ---> 0167e858013c
Step 36/49 : WORKDIR /go/src/github.com/opencontainers/runc
 ---> Using cache
 ---> 113ed8812540
Step 37/49 : RUN . /binaries-commits &&     git checkout -q "$RUNC_COMMIT" &&     make BUILDTAGS='seccomp apparmor' static && make install
 ---> Running in 8673e66f5f01
warning: empty strings as pathspecs will be made invalid in upcoming releases. please use . instead if you meant to match all paths
CGO_ENABLED=1 go build -trimpath  -tags "seccomp apparmor netgo osusergo" -ldflags "-extldflags -static -X main.gitCommit=v1.1.0-15-gc9ad96f6 -X main.version=1.1.0+dev " -o runc .
flag provided but not defined: -trimpath
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
Makefile:41: recipe for target 'static' failed
make: *** [static] Error 2
The command '/bin/sh -c . /binaries-commits &&     git checkout -q "$RUNC_COMMIT" &&     make BUILDTAGS='seccomp apparmor' static && make install' returned a non-zero code: 2
Makefile:66: recipe for target 'image-linux' failed
make[3]: *** [image-linux] Error 2
make[3]: Leaving directory '/home/jeffliu/src/docker-ce/components/packaging/image'
Makefile:130: recipe for target 'sources/engine-image' failed
make[2]: *** [sources/engine-image] Error 2
make[2]: Leaving directory '/home/jeffliu/src/docker-ce/components/packaging/deb'
Makefile:48: recipe for target 'deb' failed
make[1]: *** [deb] Error 2
make[1]: Leaving directory '/home/jeffliu/src/docker-ce/components/packaging'
Makefile:22: recipe for target 'deb' failed
make: *** [deb] Error 2

**Comment by AkihiroSuda** [comment] 2022-01-25 04:12
Please make sure your have the supported Go version (1.16 or later)
https://github.com/opencontainers/runc/tree/v1.1.0#building

**Comment by cyphar** [comment] 2022-01-25 05:09
Yeah I suspect that you're using a very old cached version of `golang:latest`. Try to do `docker pull golang:1.17-bullseye`. Maybe we should have a way to force us to do `docker build --no-cache`?

**Comment by kolyshkin** [comment] 2022-01-25 06:58
The reporter noted he's building dockerd, not runc, so I suspected (also by the number of steps) that dockerd's Dockerfile is used, not the one from this repo. However, it does not look like https://github.com/moby/moby/blob/master/Dockerfile is used here (I have also checked older branches and it does not look like it either). Seems like some custom Dockerfile.

In any case, @cnjeffliu, whatever Dockerfile you use, make sure you have a supported version of golang installed. For runc 1.1, we require Go 1.16+.

Closing as this is definitely not a bug. @cnjeffliu feel free to let us know if you think otherwise.

**Closed by kolyshkin** 2022-01-25 06:58 UTC
Labels: kind/question, go
