### ISSUE TITLE
RunC: Unable to start a container on CentOS 6 with commit b1872a0 or later

### ISSUE THREAD

**Issue by sajones** [opencontainers/runc#613] opened 2016-03-02 23:55 UTC
Prior to commit b1872a0, I could start a container using the `config.json` produced by running `runc spec` with no issues. However when I attempt to start a container using b1872a0 or later is get the following error:

```
WARN[0000] os: process already finished                 
FATA[0000] Container start failed: [10] System error: exit status 1 
```

I am not able to get any other output despite attempting all of the debug or logging options mentioned in `runc --help`.

**Comment by JakeWarner** [comment] 2016-03-03 00:27
We're currently working on this in chat, the issue is happening in runc/libcontainer/init_linux.go.

The io.Copy/ioutil.ReadAll never completes.

https://gist.github.com/JakeWarner/07810c1074ed90a4127d

**Comment by mlaventure** [comment] 2016-03-03 00:27
@sajones I have just tried on the latest master (`b86570a4d4a15f9fa2da9334e164b5f260552b4c`) and could not reproduce the issue.

Here are the command I used:
```
# mkdir bb && cd bb
# docker export $(docker create --name bb busybox) > busybox.tar
# mkdir rootfs
# tar -C rootfs -xf busybox.tar
# runc spec
# sudo runc start test
```

**Comment by crosbymichael** [comment] 2016-03-03 01:11
from irc it looks like the pid-ns pr could have something to play in this @mlaventure

**Comment by JakeWarner** [comment] 2016-03-03 01:39
Reverted my build to 5f8fd8e04e7962e137db1009a1813f3c9928dc38 (immediately before the commit @sajones  referenced), everything works there.

Fedora 22 here.

**Comment by crosbymichael** [comment] 2016-03-03 01:43
thanks. well checkout what the problem is and let you know

**Comment by JakeWarner** [comment] 2016-03-03 04:11
@sajones It turns out that I didn't have CGO_ENABLED=1 and thus wasn't building the main_unix.go file. Once I did, this issue resolved for me -- any chance this is the same issue for you?

**Comment by sajones** [comment] 2016-03-03 19:14
@JakeWarner CGO_ENABLED=1 does not seem to do much for me. Here are the steps I am using to build runc. I am using `BUILDTAGS=""` because I am building and executing runc on a system that does not have seccomp. When I ran these master was b86570a.

This works:
```
make clean
git checkout 5f8fd8e
make BUILDTAGS=""
```

These do not work:
```
make clean
git checkout b1872a0
make BUILDTAGS=""
```
```
make clean
git checkout b1872a0
CGO_ENABLED=1 make BUILDTAGS="cgo"
```
```
make clean
git checkout master
make BUILDTAGS=""
```
```
make clean
git checkout master
CGO_ENABLED=1 make BUILDTAGS="cgo"
```

**Comment by sajones** [comment] 2016-03-03 19:15
Reopening this. I hit the wrong button.

**Comment by avagin** [comment] 2016-03-03 20:41
@sajones Could you run strace -s 256 -f -o strace.log runc start ... and then share the strace.log?

**Comment by sajones** [comment] 2016-03-03 20:59
Here is the strace log from a run using the runc executable compiled by
```
make clean
git checkout master
make BUILDTAGS=""
```
[strace.log.txt](https://github.com/opencontainers/runc/files/157683/strace.log.txt)

**Comment by avagin** [comment] 2016-03-03 21:09
```
45966 clone(child_stack=0x7ffd7d984320, flags=CLONE_PARENT|CLONE_NEWNS|CLONE_NEWUTS|CLONE_NEWIPC|CLONE_NEWPID|CLONE_NEWNET|SIGCHLD) = -1 EINVAL (Invalid argument)
```

**Comment by avagin** [comment] 2016-03-03 21:13
Here is a kernel code which returns this error.
```
        /*
         * Do some preliminary argument and permissions checking before we
         * actually start allocating stuff
         */
        if (clone_flags & (CLONE_NEWUSER | CLONE_NEWPID)) {
                if (clone_flags & (CLONE_THREAD|CLONE_PARENT))
                        return -EINVAL;
```

**Comment by avagin** [comment] 2016-03-03 21:16
This code appeared in:
https://github.com/avagin/linux-task-diag/commit/40a0d32d1eaffe6aac7324ca92604b6b3977eb0e

and it was fixed here:
https://github.com/avagin/linux-task-diag/commit/1f7f4dde5c945f41a7abc2285be43d918029ecc5

**Comment by avagin** [comment] 2016-03-04 04:36
@sajones, could you try out this patch: https://github.com/avagin/runc/commit/d31e97fa28345375b3f76bff64d12cdb07e03ba0

**Comment by sajones** [comment] 2016-03-07 17:49
@avagin https://github.com/avagin/runc/commit/d31e97fa28345375b3f76bff64d12cdb07e03ba0 appears to fix the issue.

**Comment by adfernandes** [comment] 2016-03-10 13:47
I added @avagin's patch as a PR here to facilitate merging.

Full kudos to @avagin; all I did is apply and test!

**Comment by crosbymichael** [comment] 2016-03-14 18:41
The patch has been merged now, thanks for the report.

**Closed by crosbymichael** 2016-03-14 18:41 UTC
