### ISSUE TITLE
Config.json edits to run cpp and python file in the conatiner

### ISSUE THREAD

**Issue by gitsvm** [opencontainers/runc#2557] opened 2020-08-18 06:58 UTC
How should `args` parameter will look like if i want to run a cpp file my container?
currently my args section of the `config.json` file is this:
```
		"args": [
			"sh"
		],
```

**Comment by cyphar** [comment] 2020-08-19 00:26
This is a duplicate of #2556 (which you opened yesterday) as well as some criu issues that were the same too. Trust me when I say that spamming the same question doesn't get you an answer any quicker. I'll give a short response in the other thread.

**Closed by cyphar** 2020-08-19 00:26 UTC
